/* *************************************************************************** 
 * Copyrights ® 2013 Universal Music Group 
 * *************************************************************************** 
 * FileName     : RoutingLogActionType.cs
 * Project      : UMG GRCS
 * Author       : Arunagiri G
 * Created on   : 04-03-2013 
 * *************************************************************************** 
 * Modification History 
 * *************************************************************************** 
 * Modified by       Modified on     Remarks 
 * 
****************************************************************************** 
 * Reviewed by       Modified on     Remarks 
 *
****************************************************************************
 * Description     Declare Routing log action types enum

****************************************************************************/

using System.Runtime.Serialization;

namespace UMGI.GRCS.BusinessEntities.Entities.ClearanceRoutingEntities
{
    [DataContract]
    public enum RoutingLogActionType
    {
        /// <summary>
        /// Approved Action Type
        /// </summary>
        Approved = 1,

        /// <summary>
        /// ConditionallyApproved Action Type
        /// </summary>
        ConditionallyApproved = 2,

        /// <summary>
        /// Auto-Approved Action Type
        /// </summary>
        AutoApproved = 3,

        /// <summary>
        /// Rejected Action Type
        /// </summary>
        Rejected = 4,

        /// <summary>
        /// Auto-Rejected Action Type
        /// </summary>
        AutoRejected = 5,

        /// <summary>
        /// Dispatched Action Type
        /// </summary>
        Dispatched = 6,

        /// <summary>
        /// RoutedToRCCAdmin Action Type
        /// </summary>
        RoutedToRCCAdmin = 7,

        /// <summary>
        /// Re-Routed Action Type
        /// </summary>
        ReRouted = 8,

        /// <summary>
        /// Approved Action Type
        /// </summary>
        Cancelled = 9,

        /// <summary>
        /// Re-Instated Action Type
        /// </summary>
        ReInstated = 10,

        /// <summary>
        /// Excluded Action Type
        /// </summary>
        Excluded = 11,

        /// <summary>
        /// Included Action Type
        /// </summary>
        Included = 12,

        /// <summary>
        /// Re-Apply Action Type
        /// </summary>
        ReApply = 13,

        /// <summary>
        /// Remind Action Type
        /// </summary>
        Remind = 14,

        /// <summary>
        /// Resource Comment 
        /// </summary>
        ResourceComment = 15,

        /// <summary>
        /// Comment Generated by Routing Engine
        /// </summary>
        RoutingSystemComment = 16,

        /// <summary>
        /// Request Type Removed Action Type
        /// </summary>
        RequestTypeRemoved = 17,

        /// <summary>
        /// Routing Stopped Action Type
        /// </summary>
        RoutingStopped = 18,

        /// <summary>
        /// Artist Consent Action Type
        /// </summary>
        ArtistConsent = 19,

        /// <summary>
        /// Undo Artist Consent Action Type
        /// </summary>
        UndoArtistConsent = 20,

        /// <summary>
        /// Withdrawn the waiting request Action Type
        /// </summary>
        Withdrawn = 21,

        /// <summary>
        /// Move To Research Folder Action Type
        /// </summary>
        MoveToResearchFolder = 76,

        /// <summary>
        /// Move To Internal Review Folder Action Typee
        /// </summary>
        MoveToInternalReviewFolder = 77,

        /// <summary>
        /// Move To Side Artist Sample Action Type
        /// </summary>
        MoveToSideArtistSample = 78,

                /// <summary>
        /// Move To Research Folder Action Type
        /// </summary>
        UndoMoveToResearchFolder = 79,

        /// <summary>
        /// Move To Internal Review Folder Action Typee
        /// </summary>
        UndoMoveToInternalReviewFolder = 80,

        /// <summary>
        /// Move To Side Artist Sample Action Type
        /// </summary>
        UndoMoveToSideArtistSample = 81,

        /// <summary>
        /// Move To Side Artist Sample Action Type
        /// </summary>
        AssignedTo = 82
    }
}
