//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMGI.GRCS.UI.Proxies.ClearanceResourceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceSearchOption", Namespace="http://tempuri.org/")]
    public enum ResourceSearchOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        R2ResourceId = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISRC = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfClrResource", Namespace="http://tempuri.org/", ItemName="ClrResource")]
    [System.SerializableAttribute()]
    public class ArrayOfClrResource : System.Collections.Generic.List<UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClrResource> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClrResource", Namespace="http://schemas.umusic.com")]
    [System.SerializableAttribute()]
    public partial class ClrResource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClrResource.RepertoireDetailsType RepertoireDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClrResource.ClearanceDetailsType ClearanceDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClrResource.RepertoireDetailsType RepertoireDetails {
            get {
                return this.RepertoireDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RepertoireDetailsField, value) != true)) {
                    this.RepertoireDetailsField = value;
                    this.RaisePropertyChanged("RepertoireDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClrResource.ClearanceDetailsType ClearanceDetails {
            get {
                return this.ClearanceDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClearanceDetailsField, value) != true)) {
                    this.ClearanceDetailsField = value;
                    this.RaisePropertyChanged("ClearanceDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ClrResource.RepertoireDetailsType", Namespace="http://schemas.umusic.com")]
        [System.SerializableAttribute()]
        public partial class RepertoireDetailsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long GCSProjectIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long R2ReleaseIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long R2ResourceIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceResourceService.ArrayOfString RequestedCountriesField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long GCSProjectID {
                get {
                    return this.GCSProjectIDField;
                }
                set {
                    if ((this.GCSProjectIDField.Equals(value) != true)) {
                        this.GCSProjectIDField = value;
                        this.RaisePropertyChanged("GCSProjectID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long R2ReleaseID {
                get {
                    return this.R2ReleaseIDField;
                }
                set {
                    if ((this.R2ReleaseIDField.Equals(value) != true)) {
                        this.R2ReleaseIDField = value;
                        this.RaisePropertyChanged("R2ReleaseID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long R2ResourceID {
                get {
                    return this.R2ResourceIDField;
                }
                set {
                    if ((this.R2ResourceIDField.Equals(value) != true)) {
                        this.R2ResourceIDField = value;
                        this.RaisePropertyChanged("R2ResourceID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
            public UMGI.GRCS.UI.Proxies.ClearanceResourceService.ArrayOfString RequestedCountries {
                get {
                    return this.RequestedCountriesField;
                }
                set {
                    if ((object.ReferenceEquals(this.RequestedCountriesField, value) != true)) {
                        this.RequestedCountriesField = value;
                        this.RaisePropertyChanged("RequestedCountries");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ClrResource.ClearanceDetailsType", Namespace="http://schemas.umusic.com")]
        [System.SerializableAttribute()]
        public partial class ClearanceDetailsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private decimal SuggestedFeeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ExcerptTimeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool SensitiveExploitationFlagField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool GloballyClearedFlagField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Collections.Generic.List<UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClearanceResourceStatus> statusField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public decimal SuggestedFee {
                get {
                    return this.SuggestedFeeField;
                }
                set {
                    if ((this.SuggestedFeeField.Equals(value) != true)) {
                        this.SuggestedFeeField = value;
                        this.RaisePropertyChanged("SuggestedFee");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
            public string ExcerptTime {
                get {
                    return this.ExcerptTimeField;
                }
                set {
                    if ((object.ReferenceEquals(this.ExcerptTimeField, value) != true)) {
                        this.ExcerptTimeField = value;
                        this.RaisePropertyChanged("ExcerptTime");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
            public bool SensitiveExploitationFlag {
                get {
                    return this.SensitiveExploitationFlagField;
                }
                set {
                    if ((this.SensitiveExploitationFlagField.Equals(value) != true)) {
                        this.SensitiveExploitationFlagField = value;
                        this.RaisePropertyChanged("SensitiveExploitationFlag");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
            public bool GloballyClearedFlag {
                get {
                    return this.GloballyClearedFlagField;
                }
                set {
                    if ((this.GloballyClearedFlagField.Equals(value) != true)) {
                        this.GloballyClearedFlagField = value;
                        this.RaisePropertyChanged("GloballyClearedFlag");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
            public System.Collections.Generic.List<UMGI.GRCS.UI.Proxies.ClearanceResourceService.ClearanceResourceStatus> status {
                get {
                    return this.statusField;
                }
                set {
                    if ((object.ReferenceEquals(this.statusField, value) != true)) {
                        this.statusField = value;
                        this.RaisePropertyChanged("status");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.umusic.com", ItemName="CountryCode")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClearanceResourceStatus", Namespace="http://schemas.umusic.com")]
    [System.SerializableAttribute()]
    public partial class ClearanceResourceStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long Resource_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sale_Channel_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status_DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Resource_ID {
            get {
                return this.Resource_IDField;
            }
            set {
                if ((this.Resource_IDField.Equals(value) != true)) {
                    this.Resource_IDField = value;
                    this.RaisePropertyChanged("Resource_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sale_Channel_Description {
            get {
                return this.Sale_Channel_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Sale_Channel_DescriptionField, value) != true)) {
                    this.Sale_Channel_DescriptionField = value;
                    this.RaisePropertyChanged("Sale_Channel_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status_Description {
            get {
                return this.Status_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Status_DescriptionField, value) != true)) {
                    this.Status_DescriptionField = value;
                    this.RaisePropertyChanged("Status_Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClearanceResourceService.IClearanceResource")]
    public interface IClearanceResource {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceResource/SearchR2Resource", ReplyAction="http://tempuri.org/IClearanceResource/SearchR2ResourceResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ClearanceResourceEntities.ClearanceResourceSearchResult SearchR2Resource(UMGI.GRCS.BusinessEntities.Entities.ResourceEntities.ResourceSearchCriteria resourceSearch, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceResource/BG_ResourceArtist", ReplyAction="http://tempuri.org/IClearanceResource/BG_ResourceArtistResponse")]
        void BG_ResourceArtist(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ResourceEntities.ResourceInfo> resources, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceResource/RemoveResourceProject", ReplyAction="http://tempuri.org/IClearanceResource/RemoveResourceProjectResponse")]
        bool RemoveResourceProject(string archiveFlag, System.Collections.Generic.List<long> listclrResourceId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceResource/GetResourceRights", ReplyAction="http://tempuri.org/IClearanceResource/GetResourceRightsResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ContractEntities.ContractDetails> GetResourceRights(long r2resourceId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClearanceResourceChannel : UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResource, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClearanceResourceClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResource>, UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResource {
        
        public ClearanceResourceClient() {
        }
        
        public ClearanceResourceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClearanceResourceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceResourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceResourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ClearanceResourceEntities.ClearanceResourceSearchResult SearchR2Resource(UMGI.GRCS.BusinessEntities.Entities.ResourceEntities.ResourceSearchCriteria resourceSearch, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user) {
            return base.Channel.SearchR2Resource(resourceSearch, user);
        }
        
        public void BG_ResourceArtist(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ResourceEntities.ResourceInfo> resources, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user) {
            base.Channel.BG_ResourceArtist(resources, user);
        }
        
        public bool RemoveResourceProject(string archiveFlag, System.Collections.Generic.List<long> listclrResourceId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user) {
            return base.Channel.RemoveResourceProject(archiveFlag, listclrResourceId, user);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ContractEntities.ContractDetails> GetResourceRights(long r2resourceId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo user) {
            return base.Channel.GetResourceRights(r2resourceId, user);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClearanceResourceService.IClearanceResourceDataProvider")]
    public interface IClearanceResourceDataProvider {
        
        // CODEGEN: Generating message contract since element name ResourceId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceResourceDataProvider/GetGCSResource", ReplyAction="http://tempuri.org/IClearanceResourceDataProvider/GetGCSResourceResponse")]
        UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceResponse GetGCSResource(UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGCSResourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGCSResource", Namespace="http://tempuri.org/", Order=0)]
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequestBody Body;
        
        public GetGCSResourceRequest() {
        }
        
        public GetGCSResourceRequest(UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGCSResourceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResourceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GCSProjectID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.ResourceSearchOption resourceSearchOption;
        
        public GetGCSResourceRequestBody() {
        }
        
        public GetGCSResourceRequestBody(string ResourceId, string GCSProjectID, UMGI.GRCS.UI.Proxies.ClearanceResourceService.ResourceSearchOption resourceSearchOption) {
            this.ResourceId = ResourceId;
            this.GCSProjectID = GCSProjectID;
            this.resourceSearchOption = resourceSearchOption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGCSResourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGCSResourceResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceResponseBody Body;
        
        public GetGCSResourceResponse() {
        }
        
        public GetGCSResourceResponse(UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGCSResourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.ArrayOfClrResource GetGCSResourceResult;
        
        public GetGCSResourceResponseBody() {
        }
        
        public GetGCSResourceResponseBody(UMGI.GRCS.UI.Proxies.ClearanceResourceService.ArrayOfClrResource GetGCSResourceResult) {
            this.GetGCSResourceResult = GetGCSResourceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClearanceResourceDataProviderChannel : UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResourceDataProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClearanceResourceDataProviderClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResourceDataProvider>, UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResourceDataProvider {
        
        public ClearanceResourceDataProviderClient() {
        }
        
        public ClearanceResourceDataProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClearanceResourceDataProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceResourceDataProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceResourceDataProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceResponse UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResourceDataProvider.GetGCSResource(UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequest request) {
            return base.Channel.GetGCSResource(request);
        }
        
        public UMGI.GRCS.UI.Proxies.ClearanceResourceService.ArrayOfClrResource GetGCSResource(string ResourceId, string GCSProjectID, UMGI.GRCS.UI.Proxies.ClearanceResourceService.ResourceSearchOption resourceSearchOption) {
            UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequest inValue = new UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequest();
            inValue.Body = new UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceRequestBody();
            inValue.Body.ResourceId = ResourceId;
            inValue.Body.GCSProjectID = GCSProjectID;
            inValue.Body.resourceSearchOption = resourceSearchOption;
            UMGI.GRCS.UI.Proxies.ClearanceResourceService.GetGCSResourceResponse retVal = ((UMGI.GRCS.UI.Proxies.ClearanceResourceService.IClearanceResourceDataProvider)(this)).GetGCSResource(inValue);
            return retVal.Body.GetGCSResourceResult;
        }
    }
}
