//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMGI.GRCS.UI.Proxies.ArtistService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArtistService.IArtist")]
    public interface IArtist {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtist/SearchArtist", ReplyAction="http://tempuri.org/IArtist/SearchArtistResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistSearchResult SearchArtist(UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistSearchCriteria searchOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtist/SearchGRCSArtists", ReplyAction="http://tempuri.org/IArtist/SearchGRCSArtistsResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistInfo> SearchGRCSArtists(UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistInfo searchOption);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArtistChannel : UMGI.GRCS.UI.Proxies.ArtistService.IArtist, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtistClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ArtistService.IArtist>, UMGI.GRCS.UI.Proxies.ArtistService.IArtist {
        
        public ArtistClient() {
        }
        
        public ArtistClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtistClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistSearchResult SearchArtist(UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistSearchCriteria searchOption) {
            return base.Channel.SearchArtist(searchOption);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistInfo> SearchGRCSArtists(UMGI.GRCS.BusinessEntities.Entities.ArtistEntities.ArtistInfo searchOption) {
            return base.Channel.SearchGRCSArtists(searchOption);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArtistService.INotificationProcessor")]
    public interface INotificationProcessor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationProcessor/ProcessNotification", ReplyAction="http://tempuri.org/INotificationProcessor/ProcessNotificationResponse")]
        bool ProcessNotification(UMGI.GRCS.BusinessEntities.Entities.NotificationEntities.NotificationMessage notificationMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationProcessorChannel : UMGI.GRCS.UI.Proxies.ArtistService.INotificationProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationProcessorClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ArtistService.INotificationProcessor>, UMGI.GRCS.UI.Proxies.ArtistService.INotificationProcessor {
        
        public NotificationProcessorClient() {
        }
        
        public NotificationProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProcessNotification(UMGI.GRCS.BusinessEntities.Entities.NotificationEntities.NotificationMessage notificationMessage) {
            return base.Channel.ProcessNotification(notificationMessage);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArtistService.IArtistDataProvider")]
    public interface IArtistDataProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistDataProvider/GetArtistRights", ReplyAction="http://tempuri.org/IArtistDataProvider/GetArtistRightsResponse")]
        UMGI.GRCS.BusinessEntities.Entities.NotificationEntities.ArtistRights GetArtistRights(string r2Talentnameid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArtistDataProviderChannel : UMGI.GRCS.UI.Proxies.ArtistService.IArtistDataProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtistDataProviderClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ArtistService.IArtistDataProvider>, UMGI.GRCS.UI.Proxies.ArtistService.IArtistDataProvider {
        
        public ArtistDataProviderClient() {
        }
        
        public ArtistDataProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtistDataProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistDataProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistDataProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.NotificationEntities.ArtistRights GetArtistRights(string r2Talentnameid) {
            return base.Channel.GetArtistRights(r2Talentnameid);
        }
    }
}
