//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMGI.GRCS.UI.Proxies.ClearanceReleaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReleaseSearchOption", Namespace="http://tempuri.org/")]
    public enum ReleaseSearchOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        R2ReleaseId = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GCSReleaseId = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfClrRelease", Namespace="http://tempuri.org/", ItemName="ClrRelease")]
    [System.SerializableAttribute()]
    public class ArrayOfClrRelease : System.Collections.Generic.List<UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease", Namespace="http://schemas.umusic.com")]
    [System.SerializableAttribute()]
    public partial class ClrRelease : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.RepertoireDetailsType RepertoireDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType ClearanceDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.RepertoireDetailsType RepertoireDetails {
            get {
                return this.RepertoireDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RepertoireDetailsField, value) != true)) {
                    this.RepertoireDetailsField = value;
                    this.RaisePropertyChanged("RepertoireDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType ClearanceDetails {
            get {
                return this.ClearanceDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClearanceDetailsField, value) != true)) {
                    this.ClearanceDetailsField = value;
                    this.RaisePropertyChanged("ClearanceDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.RepertoireDetailsType", Namespace="http://schemas.umusic.com")]
        [System.SerializableAttribute()]
        public partial class RepertoireDetailsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long GCSProjectIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long GCSReleaseIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string UPCField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TitleField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string VersionTitleField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ArrayOfPositiveInteger ArtistField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long LabelField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string MusicTypeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string SoundTrackField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long NumberOfTracksField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PackageField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long NumberOfComponentsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ConfigurationField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ConfigurationGroupField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long R2ReleaseIDField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long GCSProjectID {
                get {
                    return this.GCSProjectIDField;
                }
                set {
                    if ((this.GCSProjectIDField.Equals(value) != true)) {
                        this.GCSProjectIDField = value;
                        this.RaisePropertyChanged("GCSProjectID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long GCSReleaseID {
                get {
                    return this.GCSReleaseIDField;
                }
                set {
                    if ((this.GCSReleaseIDField.Equals(value) != true)) {
                        this.GCSReleaseIDField = value;
                        this.RaisePropertyChanged("GCSReleaseID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
            public string UPC {
                get {
                    return this.UPCField;
                }
                set {
                    if ((object.ReferenceEquals(this.UPCField, value) != true)) {
                        this.UPCField = value;
                        this.RaisePropertyChanged("UPC");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
            public string Title {
                get {
                    return this.TitleField;
                }
                set {
                    if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                        this.TitleField = value;
                        this.RaisePropertyChanged("Title");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
            public string VersionTitle {
                get {
                    return this.VersionTitleField;
                }
                set {
                    if ((object.ReferenceEquals(this.VersionTitleField, value) != true)) {
                        this.VersionTitleField = value;
                        this.RaisePropertyChanged("VersionTitle");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ArrayOfPositiveInteger Artist {
                get {
                    return this.ArtistField;
                }
                set {
                    if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                        this.ArtistField = value;
                        this.RaisePropertyChanged("Artist");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
            public long Label {
                get {
                    return this.LabelField;
                }
                set {
                    if ((this.LabelField.Equals(value) != true)) {
                        this.LabelField = value;
                        this.RaisePropertyChanged("Label");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
            public string MusicType {
                get {
                    return this.MusicTypeField;
                }
                set {
                    if ((object.ReferenceEquals(this.MusicTypeField, value) != true)) {
                        this.MusicTypeField = value;
                        this.RaisePropertyChanged("MusicType");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
            public string SoundTrack {
                get {
                    return this.SoundTrackField;
                }
                set {
                    if ((object.ReferenceEquals(this.SoundTrackField, value) != true)) {
                        this.SoundTrackField = value;
                        this.RaisePropertyChanged("SoundTrack");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
            public long NumberOfTracks {
                get {
                    return this.NumberOfTracksField;
                }
                set {
                    if ((this.NumberOfTracksField.Equals(value) != true)) {
                        this.NumberOfTracksField = value;
                        this.RaisePropertyChanged("NumberOfTracks");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
            public string Package {
                get {
                    return this.PackageField;
                }
                set {
                    if ((object.ReferenceEquals(this.PackageField, value) != true)) {
                        this.PackageField = value;
                        this.RaisePropertyChanged("Package");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
            public long NumberOfComponents {
                get {
                    return this.NumberOfComponentsField;
                }
                set {
                    if ((this.NumberOfComponentsField.Equals(value) != true)) {
                        this.NumberOfComponentsField = value;
                        this.RaisePropertyChanged("NumberOfComponents");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
            public string Configuration {
                get {
                    return this.ConfigurationField;
                }
                set {
                    if ((object.ReferenceEquals(this.ConfigurationField, value) != true)) {
                        this.ConfigurationField = value;
                        this.RaisePropertyChanged("Configuration");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
            public string ConfigurationGroup {
                get {
                    return this.ConfigurationGroupField;
                }
                set {
                    if ((object.ReferenceEquals(this.ConfigurationGroupField, value) != true)) {
                        this.ConfigurationGroupField = value;
                        this.RaisePropertyChanged("ConfigurationGroup");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
            public long R2ReleaseID {
                get {
                    return this.R2ReleaseIDField;
                }
                set {
                    if ((this.R2ReleaseIDField.Equals(value) != true)) {
                        this.R2ReleaseIDField = value;
                        this.RaisePropertyChanged("R2ReleaseID");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType", Namespace="http://schemas.umusic.com")]
        [System.SerializableAttribute()]
        public partial class ClearanceDetailsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.RegularRetailType RegularRetailField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.ClubType ClubField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.NonTraditionType NonTraditionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.PromotionalType PromotionalField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.TVRadioBreakICLAType TVRadioBreakICLAField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.PriceReductionType PriceReductionField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.RegularRetailType RegularRetail {
                get {
                    return this.RegularRetailField;
                }
                set {
                    if ((object.ReferenceEquals(this.RegularRetailField, value) != true)) {
                        this.RegularRetailField = value;
                        this.RaisePropertyChanged("RegularRetail");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.ClubType Club {
                get {
                    return this.ClubField;
                }
                set {
                    if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                        this.ClubField = value;
                        this.RaisePropertyChanged("Club");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.NonTraditionType NonTradition {
                get {
                    return this.NonTraditionField;
                }
                set {
                    if ((object.ReferenceEquals(this.NonTraditionField, value) != true)) {
                        this.NonTraditionField = value;
                        this.RaisePropertyChanged("NonTradition");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.PromotionalType Promotional {
                get {
                    return this.PromotionalField;
                }
                set {
                    if ((object.ReferenceEquals(this.PromotionalField, value) != true)) {
                        this.PromotionalField = value;
                        this.RaisePropertyChanged("Promotional");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.TVRadioBreakICLAType TVRadioBreakICLA {
                get {
                    return this.TVRadioBreakICLAField;
                }
                set {
                    if ((object.ReferenceEquals(this.TVRadioBreakICLAField, value) != true)) {
                        this.TVRadioBreakICLAField = value;
                        this.RaisePropertyChanged("TVRadioBreakICLA");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
            public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ClrRelease.ClearanceDetailsType.PriceReductionType PriceReduction {
                get {
                    return this.PriceReductionField;
                }
                set {
                    if ((object.ReferenceEquals(this.PriceReductionField, value) != true)) {
                        this.PriceReductionField = value;
                        this.RaisePropertyChanged("PriceReduction");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType.RegularRetailType", Namespace="http://schemas.umusic.com")]
            [System.SerializableAttribute()]
            public partial class RegularRetailType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string PriceLevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string ICLALevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool DeviatedICLAlevelFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DeviatedICLAlevelField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string PriceLevel {
                    get {
                        return this.PriceLevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.PriceLevelField, value) != true)) {
                            this.PriceLevelField = value;
                            this.RaisePropertyChanged("PriceLevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string ICLALevel {
                    get {
                        return this.ICLALevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ICLALevelField, value) != true)) {
                            this.ICLALevelField = value;
                            this.RaisePropertyChanged("ICLALevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
                public bool DeviatedICLAlevelFlag {
                    get {
                        return this.DeviatedICLAlevelFlagField;
                    }
                    set {
                        if ((this.DeviatedICLAlevelFlagField.Equals(value) != true)) {
                            this.DeviatedICLAlevelFlagField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevelFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
                public string DeviatedICLAlevel {
                    get {
                        return this.DeviatedICLAlevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DeviatedICLAlevelField, value) != true)) {
                            this.DeviatedICLAlevelField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevel");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType.ClubType", Namespace="http://schemas.umusic.com")]
            [System.SerializableAttribute()]
            public partial class ClubType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string PriceLevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string ICLALevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool DeviatedICLAlevelFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DeviatedICLAlevelField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string PriceLevel {
                    get {
                        return this.PriceLevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.PriceLevelField, value) != true)) {
                            this.PriceLevelField = value;
                            this.RaisePropertyChanged("PriceLevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string ICLALevel {
                    get {
                        return this.ICLALevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ICLALevelField, value) != true)) {
                            this.ICLALevelField = value;
                            this.RaisePropertyChanged("ICLALevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
                public bool DeviatedICLAlevelFlag {
                    get {
                        return this.DeviatedICLAlevelFlagField;
                    }
                    set {
                        if ((this.DeviatedICLAlevelFlagField.Equals(value) != true)) {
                            this.DeviatedICLAlevelFlagField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevelFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
                public string DeviatedICLAlevel {
                    get {
                        return this.DeviatedICLAlevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DeviatedICLAlevelField, value) != true)) {
                            this.DeviatedICLAlevelField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevel");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType.NonTraditionType", Namespace="http://schemas.umusic.com")]
            [System.SerializableAttribute()]
            public partial class NonTraditionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string ICLALevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool DeviatedICLAlevelFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DeviatedICLAlevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool ICLAFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool SuggestedFeeFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long InvoicePriceField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long SellingPriceLessVATField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long ICLAAccountingBaseField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long ResourceFeeField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long DeemedPPDField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string ICLALevel {
                    get {
                        return this.ICLALevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ICLALevelField, value) != true)) {
                            this.ICLALevelField = value;
                            this.RaisePropertyChanged("ICLALevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
                public bool DeviatedICLAlevelFlag {
                    get {
                        return this.DeviatedICLAlevelFlagField;
                    }
                    set {
                        if ((this.DeviatedICLAlevelFlagField.Equals(value) != true)) {
                            this.DeviatedICLAlevelFlagField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevelFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
                public string DeviatedICLAlevel {
                    get {
                        return this.DeviatedICLAlevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DeviatedICLAlevelField, value) != true)) {
                            this.DeviatedICLAlevelField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
                public bool ICLAFlag {
                    get {
                        return this.ICLAFlagField;
                    }
                    set {
                        if ((this.ICLAFlagField.Equals(value) != true)) {
                            this.ICLAFlagField = value;
                            this.RaisePropertyChanged("ICLAFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
                public bool SuggestedFeeFlag {
                    get {
                        return this.SuggestedFeeFlagField;
                    }
                    set {
                        if ((this.SuggestedFeeFlagField.Equals(value) != true)) {
                            this.SuggestedFeeFlagField = value;
                            this.RaisePropertyChanged("SuggestedFeeFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
                public long InvoicePrice {
                    get {
                        return this.InvoicePriceField;
                    }
                    set {
                        if ((this.InvoicePriceField.Equals(value) != true)) {
                            this.InvoicePriceField = value;
                            this.RaisePropertyChanged("InvoicePrice");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
                public long SellingPriceLessVAT {
                    get {
                        return this.SellingPriceLessVATField;
                    }
                    set {
                        if ((this.SellingPriceLessVATField.Equals(value) != true)) {
                            this.SellingPriceLessVATField = value;
                            this.RaisePropertyChanged("SellingPriceLessVAT");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
                public long ICLAAccountingBase {
                    get {
                        return this.ICLAAccountingBaseField;
                    }
                    set {
                        if ((this.ICLAAccountingBaseField.Equals(value) != true)) {
                            this.ICLAAccountingBaseField = value;
                            this.RaisePropertyChanged("ICLAAccountingBase");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
                public long ResourceFee {
                    get {
                        return this.ResourceFeeField;
                    }
                    set {
                        if ((this.ResourceFeeField.Equals(value) != true)) {
                            this.ResourceFeeField = value;
                            this.RaisePropertyChanged("ResourceFee");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
                public long DeemedPPD {
                    get {
                        return this.DeemedPPDField;
                    }
                    set {
                        if ((this.DeemedPPDField.Equals(value) != true)) {
                            this.DeemedPPDField = value;
                            this.RaisePropertyChanged("DeemedPPD");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType.PromotionalType", Namespace="http://schemas.umusic.com")]
            [System.SerializableAttribute()]
            public partial class PromotionalType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string PriceLevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string ICLALevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool DeviatedICLAlevelFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DeviatedICLAlevelField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string PriceLevel {
                    get {
                        return this.PriceLevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.PriceLevelField, value) != true)) {
                            this.PriceLevelField = value;
                            this.RaisePropertyChanged("PriceLevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string ICLALevel {
                    get {
                        return this.ICLALevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ICLALevelField, value) != true)) {
                            this.ICLALevelField = value;
                            this.RaisePropertyChanged("ICLALevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
                public bool DeviatedICLAlevelFlag {
                    get {
                        return this.DeviatedICLAlevelFlagField;
                    }
                    set {
                        if ((this.DeviatedICLAlevelFlagField.Equals(value) != true)) {
                            this.DeviatedICLAlevelFlagField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevelFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
                public string DeviatedICLAlevel {
                    get {
                        return this.DeviatedICLAlevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DeviatedICLAlevelField, value) != true)) {
                            this.DeviatedICLAlevelField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevel");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType.TVRadioBreakICLAType", Namespace="http://schemas.umusic.com")]
            [System.SerializableAttribute()]
            public partial class TVRadioBreakICLAType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string PriceLevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string ICLALevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool DeviatedICLAlevelFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DeviatedICLAlevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long ExactPPDField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private long EstimatedRetailField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string PriceLevel {
                    get {
                        return this.PriceLevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.PriceLevelField, value) != true)) {
                            this.PriceLevelField = value;
                            this.RaisePropertyChanged("PriceLevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string ICLALevel {
                    get {
                        return this.ICLALevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ICLALevelField, value) != true)) {
                            this.ICLALevelField = value;
                            this.RaisePropertyChanged("ICLALevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
                public bool DeviatedICLAlevelFlag {
                    get {
                        return this.DeviatedICLAlevelFlagField;
                    }
                    set {
                        if ((this.DeviatedICLAlevelFlagField.Equals(value) != true)) {
                            this.DeviatedICLAlevelFlagField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevelFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
                public string DeviatedICLAlevel {
                    get {
                        return this.DeviatedICLAlevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DeviatedICLAlevelField, value) != true)) {
                            this.DeviatedICLAlevelField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
                public long ExactPPD {
                    get {
                        return this.ExactPPDField;
                    }
                    set {
                        if ((this.ExactPPDField.Equals(value) != true)) {
                            this.ExactPPDField = value;
                            this.RaisePropertyChanged("ExactPPD");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
                public long EstimatedRetail {
                    get {
                        return this.EstimatedRetailField;
                    }
                    set {
                        if ((this.EstimatedRetailField.Equals(value) != true)) {
                            this.EstimatedRetailField = value;
                            this.RaisePropertyChanged("EstimatedRetail");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ClrRelease.ClearanceDetailsType.PriceReductionType", Namespace="http://schemas.umusic.com")]
            [System.SerializableAttribute()]
            public partial class PriceReductionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string PriceLevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string ICLALevelField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private bool DeviatedICLAlevelFlagField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DeviatedICLAlevelField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
                public string PriceLevel {
                    get {
                        return this.PriceLevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.PriceLevelField, value) != true)) {
                            this.PriceLevelField = value;
                            this.RaisePropertyChanged("PriceLevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string ICLALevel {
                    get {
                        return this.ICLALevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.ICLALevelField, value) != true)) {
                            this.ICLALevelField = value;
                            this.RaisePropertyChanged("ICLALevel");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
                public bool DeviatedICLAlevelFlag {
                    get {
                        return this.DeviatedICLAlevelFlagField;
                    }
                    set {
                        if ((this.DeviatedICLAlevelFlagField.Equals(value) != true)) {
                            this.DeviatedICLAlevelFlagField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevelFlag");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
                public string DeviatedICLAlevel {
                    get {
                        return this.DeviatedICLAlevelField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DeviatedICLAlevelField, value) != true)) {
                            this.DeviatedICLAlevelField = value;
                            this.RaisePropertyChanged("DeviatedICLAlevel");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPositiveInteger", Namespace="http://schemas.umusic.com", ItemName="R2TalentNameID")]
    [System.SerializableAttribute()]
    public class ArrayOfPositiveInteger : System.Collections.Generic.List<long> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClearanceReleaseService.IClearanceRelease")]
    public interface IClearanceRelease {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetReleaseLabelList", ReplyAction="http://tempuri.org/IClearanceRelease/GetReleaseLabelListResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> GetReleaseLabelList(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetReleaseConfigList", ReplyAction="http://tempuri.org/IClearanceRelease/GetReleaseConfigListResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> GetReleaseConfigList(string ConfigGroupId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetReleaseConfigGroupList", ReplyAction="http://tempuri.org/IClearanceRelease/GetReleaseConfigGroupListResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> GetReleaseConfigGroupList(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/SaveReleaseNew", ReplyAction="http://tempuri.org/IClearanceRelease/SaveReleaseNewResponse")]
        string SaveReleaseNew(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> clearanceRelease, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetExistingReleases", ReplyAction="http://tempuri.org/IClearanceRelease/GetExistingReleasesResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceReleaseSearchResult GetExistingReleases(string UPC, string ReleaseTitle, string ArtistName, int ArtistID, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetExistingReleasesSaveMode", ReplyAction="http://tempuri.org/IClearanceRelease/GetExistingReleasesSaveModeResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceReleaseSearchResult GetExistingReleasesSaveMode(string projectCode, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/SaveExistingReleases", ReplyAction="http://tempuri.org/IClearanceRelease/SaveExistingReleasesResponse")]
        string SaveExistingReleases(UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceReleaseSearchResult releaseSearchResult, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GeDeviatedIclaLevel", ReplyAction="http://tempuri.org/IClearanceRelease/GeDeviatedIclaLevelResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.DropDeviatedICLALevel> GeDeviatedIclaLevel(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetPriceLevel", ReplyAction="http://tempuri.org/IClearanceRelease/GetPriceLevelResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.DropPriceLevel> GetPriceLevel(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/BG_ReleaseDetails", ReplyAction="http://tempuri.org/IClearanceRelease/BG_ReleaseDetailsResponse")]
        void BG_ReleaseDetails(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseInfo> releases, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo, long clearanceProjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GCSReleaseSearch", ReplyAction="http://tempuri.org/IClearanceRelease/GCSReleaseSearchResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseSearchResult GCSReleaseSearch(UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseSearchCriteria searchCriteria, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/R2GetReleaseAdditionalDetails", ReplyAction="http://tempuri.org/IClearanceRelease/R2GetReleaseAdditionalDetailsResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ProjectEntities.TrackInfo> R2GetReleaseAdditionalDetails(long releaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetUPCNumber", ReplyAction="http://tempuri.org/IClearanceRelease/GetUPCNumberResponse")]
        string GetUPCNumber(System.Collections.Generic.List<long> classiceReleaseId, System.Collections.Generic.List<long> nonClassiceReleaseId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetUpc_Check_Digit", ReplyAction="http://tempuri.org/IClearanceRelease/GetUpc_Check_DigitResponse")]
        string GetUpc_Check_Digit(string upcNumber, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/RemoveUPCNumber", ReplyAction="http://tempuri.org/IClearanceRelease/RemoveUPCNumberResponse")]
        bool RemoveUPCNumber(long projectReleaseId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetReleaseAdditionalDetails", ReplyAction="http://tempuri.org/IClearanceRelease/GetReleaseAdditionalDetailsResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease GetReleaseAdditionalDetails(long releaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetReleaseDetailsGCS", ReplyAction="http://tempuri.org/IClearanceRelease/GetReleaseDetailsGCSResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease GetReleaseDetailsGCS(long releaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetExistingR2ReleaseIdFromGcs", ReplyAction="http://tempuri.org/IClearanceRelease/GetExistingR2ReleaseIdFromGcsResponse")]
        System.Collections.Generic.List<System.Nullable<long>> GetExistingR2ReleaseIdFromGcs(System.Collections.Generic.List<System.Nullable<long>> r2ReleaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetExistingR2ReleaseIdForPackage", ReplyAction="http://tempuri.org/IClearanceRelease/GetExistingR2ReleaseIdForPackageResponse")]
        System.Collections.Generic.List<long> GetExistingR2ReleaseIdForPackage(System.Collections.Generic.List<long> r2ReleaseId, System.Nullable<long> ParentReleaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/UpdatePackage", ReplyAction="http://tempuri.org/IClearanceRelease/UpdatePackageResponse")]
        System.Collections.Generic.List<long> UpdatePackage(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ProjectEntities.PackageInfo> packageInfo, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetPackageDetailsforProjectRelease", ReplyAction="http://tempuri.org/IClearanceRelease/GetPackageDetailsforProjectReleaseResponse")]
        System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ProjectEntities.PackageInfo> GetPackageDetailsforProjectRelease(long ReleaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/getLabelNmForExistingRelease", ReplyAction="http://tempuri.org/IClearanceRelease/getLabelNmForExistingReleaseResponse")]
        string getLabelNmForExistingRelease(int LabelId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/UpdateManualUpc", ReplyAction="http://tempuri.org/IClearanceRelease/UpdateManualUpcResponse")]
        string UpdateManualUpc(long releaseId, string upcNumber, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceRelease/GetReleaseDetailsBasedonR2ReleaseId", ReplyAction="http://tempuri.org/IClearanceRelease/GetReleaseDetailsBasedonR2ReleaseIdResponse")]
        UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseSearchResult GetReleaseDetailsBasedonR2ReleaseId(System.Collections.Generic.List<long> R2ReleaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClearanceReleaseChannel : UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceRelease, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClearanceReleaseClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceRelease>, UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceRelease {
        
        public ClearanceReleaseClient() {
        }
        
        public ClearanceReleaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClearanceReleaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceReleaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceReleaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> GetReleaseLabelList(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetReleaseLabelList(userInfo);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> GetReleaseConfigList(string ConfigGroupId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetReleaseConfigList(ConfigGroupId, userInfo);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> GetReleaseConfigGroupList(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetReleaseConfigGroupList(userInfo);
        }
        
        public string SaveReleaseNew(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease> clearanceRelease, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.SaveReleaseNew(clearanceRelease, userInfo);
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceReleaseSearchResult GetExistingReleases(string UPC, string ReleaseTitle, string ArtistName, int ArtistID, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetExistingReleases(UPC, ReleaseTitle, ArtistName, ArtistID, userInfo);
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceReleaseSearchResult GetExistingReleasesSaveMode(string projectCode, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetExistingReleasesSaveMode(projectCode, userInfo);
        }
        
        public string SaveExistingReleases(UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceReleaseSearchResult releaseSearchResult, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.SaveExistingReleases(releaseSearchResult, userInfo);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.DropDeviatedICLALevel> GeDeviatedIclaLevel(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GeDeviatedIclaLevel(userInfo);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.DropPriceLevel> GetPriceLevel(UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetPriceLevel(userInfo);
        }
        
        public void BG_ReleaseDetails(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseInfo> releases, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo, long clearanceProjectID) {
            base.Channel.BG_ReleaseDetails(releases, userInfo, clearanceProjectID);
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseSearchResult GCSReleaseSearch(UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseSearchCriteria searchCriteria, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GCSReleaseSearch(searchCriteria, userInfo);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ProjectEntities.TrackInfo> R2GetReleaseAdditionalDetails(long releaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.R2GetReleaseAdditionalDetails(releaseId, userInfo);
        }
        
        public string GetUPCNumber(System.Collections.Generic.List<long> classiceReleaseId, System.Collections.Generic.List<long> nonClassiceReleaseId, string userId) {
            return base.Channel.GetUPCNumber(classiceReleaseId, nonClassiceReleaseId, userId);
        }
        
        public string GetUpc_Check_Digit(string upcNumber, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetUpc_Check_Digit(upcNumber, userInfo);
        }
        
        public bool RemoveUPCNumber(long projectReleaseId, string userId) {
            return base.Channel.RemoveUPCNumber(projectReleaseId, userId);
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease GetReleaseAdditionalDetails(long releaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetReleaseAdditionalDetails(releaseId, userInfo);
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ClearanceReleaseEntities.ClearanceRelease GetReleaseDetailsGCS(long releaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetReleaseDetailsGCS(releaseId, userInfo);
        }
        
        public System.Collections.Generic.List<System.Nullable<long>> GetExistingR2ReleaseIdFromGcs(System.Collections.Generic.List<System.Nullable<long>> r2ReleaseId) {
            return base.Channel.GetExistingR2ReleaseIdFromGcs(r2ReleaseId);
        }
        
        public System.Collections.Generic.List<long> GetExistingR2ReleaseIdForPackage(System.Collections.Generic.List<long> r2ReleaseId, System.Nullable<long> ParentReleaseId) {
            return base.Channel.GetExistingR2ReleaseIdForPackage(r2ReleaseId, ParentReleaseId);
        }
        
        public System.Collections.Generic.List<long> UpdatePackage(System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ProjectEntities.PackageInfo> packageInfo, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.UpdatePackage(packageInfo, userInfo);
        }
        
        public System.Collections.Generic.List<UMGI.GRCS.BusinessEntities.Entities.ProjectEntities.PackageInfo> GetPackageDetailsforProjectRelease(long ReleaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetPackageDetailsforProjectRelease(ReleaseId, userInfo);
        }
        
        public string getLabelNmForExistingRelease(int LabelId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.getLabelNmForExistingRelease(LabelId, userInfo);
        }
        
        public string UpdateManualUpc(long releaseId, string upcNumber, string userId) {
            return base.Channel.UpdateManualUpc(releaseId, upcNumber, userId);
        }
        
        public UMGI.GRCS.BusinessEntities.Entities.ReleaseEntities.ReleaseSearchResult GetReleaseDetailsBasedonR2ReleaseId(System.Collections.Generic.List<long> R2ReleaseId, UMGI.GRCS.BusinessEntities.Entities.BaseEntities.LeanUserInfo userInfo) {
            return base.Channel.GetReleaseDetailsBasedonR2ReleaseId(R2ReleaseId, userInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClearanceReleaseService.IClearanceReleaseDataProvider")]
    public interface IClearanceReleaseDataProvider {
        
        // CODEGEN: Generating message contract since element name ReleaseId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClearanceReleaseDataProvider/GetGCSRelease", ReplyAction="http://tempuri.org/IClearanceReleaseDataProvider/GetGCSReleaseResponse")]
        UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseResponse GetGCSRelease(UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGCSReleaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGCSRelease", Namespace="http://tempuri.org/", Order=0)]
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequestBody Body;
        
        public GetGCSReleaseRequest() {
        }
        
        public GetGCSReleaseRequest(UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGCSReleaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReleaseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GCSProjectID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ReleaseSearchOption releaseSearchOption;
        
        public GetGCSReleaseRequestBody() {
        }
        
        public GetGCSReleaseRequestBody(string ReleaseId, string GCSProjectID, UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ReleaseSearchOption releaseSearchOption) {
            this.ReleaseId = ReleaseId;
            this.GCSProjectID = GCSProjectID;
            this.releaseSearchOption = releaseSearchOption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGCSReleaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGCSReleaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseResponseBody Body;
        
        public GetGCSReleaseResponse() {
        }
        
        public GetGCSReleaseResponse(UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGCSReleaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ArrayOfClrRelease GetGCSReleaseResult;
        
        public GetGCSReleaseResponseBody() {
        }
        
        public GetGCSReleaseResponseBody(UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ArrayOfClrRelease GetGCSReleaseResult) {
            this.GetGCSReleaseResult = GetGCSReleaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClearanceReleaseDataProviderChannel : UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceReleaseDataProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClearanceReleaseDataProviderClient : System.ServiceModel.ClientBase<UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceReleaseDataProvider>, UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceReleaseDataProvider {
        
        public ClearanceReleaseDataProviderClient() {
        }
        
        public ClearanceReleaseDataProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClearanceReleaseDataProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceReleaseDataProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClearanceReleaseDataProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseResponse UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceReleaseDataProvider.GetGCSRelease(UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequest request) {
            return base.Channel.GetGCSRelease(request);
        }
        
        public UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ArrayOfClrRelease GetGCSRelease(string ReleaseId, string GCSProjectID, UMGI.GRCS.UI.Proxies.ClearanceReleaseService.ReleaseSearchOption releaseSearchOption) {
            UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequest inValue = new UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequest();
            inValue.Body = new UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseRequestBody();
            inValue.Body.ReleaseId = ReleaseId;
            inValue.Body.GCSProjectID = GCSProjectID;
            inValue.Body.releaseSearchOption = releaseSearchOption;
            UMGI.GRCS.UI.Proxies.ClearanceReleaseService.GetGCSReleaseResponse retVal = ((UMGI.GRCS.UI.Proxies.ClearanceReleaseService.IClearanceReleaseDataProvider)(this)).GetGCSRelease(inValue);
            return retVal.Body.GetGCSReleaseResult;
        }
    }
}
