//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/WSReleaseInformation/", ConfigurationName="WSReleaseInformation")]
public interface WSReleaseInformation
{
    
    // CODEGEN: Parameter 'Release' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/WSReleaseInformation/GetFullRelease", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Release")]
    GetFullReleaseResponse GetFullRelease(GetFullReleaseRequest request);
    
    // CODEGEN: Parameter 'Release' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/WSReleaseInformation/GetReleaseWithoutWorkflow", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Release")]
    GetReleaseWithoutWorkflowResponse GetReleaseWithoutWorkflow(GetReleaseWithoutWorkflowRequest request);
    
    // CODEGEN: Parameter 'Release' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/WSReleaseInformation/GetReleaseWithoutMasterChild", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Release")]
    GetReleaseWithoutMasterChildResponse GetReleaseWithoutMasterChild(GetReleaseWithoutMasterChildRequest request);
    
    // CODEGEN: Parameter 'Release' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/WSReleaseInformation/GetReleaseWithoutMasterChildAndWorkfl" +
        "ow", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Release")]
    GetReleaseWithoutMasterChildAndWorkflowResponse GetReleaseWithoutMasterChildAndWorkflow(GetReleaseWithoutMasterChildAndWorkflowRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class ReleaseScheduleInformationType
{
    
    private string uPCField;
    
    private string catalogNumberField;
    
    private string internalIdentifierField;
    
    private string statusField;
    
    private LabelCopyMetadataType labelCopyMetadataField;
    
    private string coreReleaseDateField;
    
    private System.DateTime earliestReleaseDateField;
    
    private bool earliestReleaseDateFieldSpecified;
    
    private bool hasMarketingRestrictionField;
    
    private bool hasPreOrderField;
    
    private string keyContactField;
    
    private string sourceField;
    
    private ManagementType managementField;
    
    private System.DateTime lastUpdateDateField;
    
    private MasterChildRelationshipType masterChildRelationshipField;
    
    private CountryType[] countriesField;
    
    private StepType[] workflowField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string UPC
    {
        get
        {
            return this.uPCField;
        }
        set
        {
            this.uPCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string CatalogNumber
    {
        get
        {
            return this.catalogNumberField;
        }
        set
        {
            this.catalogNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=2)]
    public string InternalIdentifier
    {
        get
        {
            return this.internalIdentifierField;
        }
        set
        {
            this.internalIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public LabelCopyMetadataType LabelCopyMetadata
    {
        get
        {
            return this.labelCopyMetadataField;
        }
        set
        {
            this.labelCopyMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string CoreReleaseDate
    {
        get
        {
            return this.coreReleaseDateField;
        }
        set
        {
            this.coreReleaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
    public System.DateTime EarliestReleaseDate
    {
        get
        {
            return this.earliestReleaseDateField;
        }
        set
        {
            this.earliestReleaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EarliestReleaseDateSpecified
    {
        get
        {
            return this.earliestReleaseDateFieldSpecified;
        }
        set
        {
            this.earliestReleaseDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public bool HasMarketingRestriction
    {
        get
        {
            return this.hasMarketingRestrictionField;
        }
        set
        {
            this.hasMarketingRestrictionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public bool HasPreOrder
    {
        get
        {
            return this.hasPreOrderField;
        }
        set
        {
            this.hasPreOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string KeyContact
    {
        get
        {
            return this.keyContactField;
        }
        set
        {
            this.keyContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string Source
    {
        get
        {
            return this.sourceField;
        }
        set
        {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public ManagementType Management
    {
        get
        {
            return this.managementField;
        }
        set
        {
            this.managementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=12)]
    public System.DateTime LastUpdateDate
    {
        get
        {
            return this.lastUpdateDateField;
        }
        set
        {
            this.lastUpdateDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public MasterChildRelationshipType MasterChildRelationship
    {
        get
        {
            return this.masterChildRelationshipField;
        }
        set
        {
            this.masterChildRelationshipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Country", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CountryType[] Countries
    {
        get
        {
            return this.countriesField;
        }
        set
        {
            this.countriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Step", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public StepType[] Workflow
    {
        get
        {
            return this.workflowField;
        }
        set
        {
            this.workflowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class LabelCopyMetadataType
{
    
    private string artistNameField;
    
    private string titleField;
    
    private string versionTitleField;
    
    private bool hasExplicitLyricsField;
    
    private bool hasExplicitLyricsFieldSpecified;
    
    private string dSchedOwningCountryField;
    
    private string accountIdField;
    
    private string productConfigurationField;
    
    private string musicTypeField;
    
    private string resolutionTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ArtistName
    {
        get
        {
            return this.artistNameField;
        }
        set
        {
            this.artistNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string VersionTitle
    {
        get
        {
            return this.versionTitleField;
        }
        set
        {
            this.versionTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public bool HasExplicitLyrics
    {
        get
        {
            return this.hasExplicitLyricsField;
        }
        set
        {
            this.hasExplicitLyricsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HasExplicitLyricsSpecified
    {
        get
        {
            return this.hasExplicitLyricsFieldSpecified;
        }
        set
        {
            this.hasExplicitLyricsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string DSchedOwningCountry
    {
        get
        {
            return this.dSchedOwningCountryField;
        }
        set
        {
            this.dSchedOwningCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=5)]
    public string AccountId
    {
        get
        {
            return this.accountIdField;
        }
        set
        {
            this.accountIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=6)]
    public string ProductConfiguration
    {
        get
        {
            return this.productConfigurationField;
        }
        set
        {
            this.productConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string MusicType
    {
        get
        {
            return this.musicTypeField;
        }
        set
        {
            this.musicTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string ResolutionType
    {
        get
        {
            return this.resolutionTypeField;
        }
        set
        {
            this.resolutionTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class StepType
{
    
    private string stepNameField;
    
    private bool isCompleteField;
    
    private System.DateTime completionDateField;
    
    private bool completionDateFieldSpecified;
    
    private string sequenceNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string StepName
    {
        get
        {
            return this.stepNameField;
        }
        set
        {
            this.stepNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public bool IsComplete
    {
        get
        {
            return this.isCompleteField;
        }
        set
        {
            this.isCompleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
    public System.DateTime CompletionDate
    {
        get
        {
            return this.completionDateField;
        }
        set
        {
            this.completionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompletionDateSpecified
    {
        get
        {
            return this.completionDateFieldSpecified;
        }
        set
        {
            this.completionDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=3)]
    public string SequenceNumber
    {
        get
        {
            return this.sequenceNumberField;
        }
        set
        {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class OrgStructureType
{
    
    private string companyIdField;
    
    private string divisionIdField;
    
    private string labelIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=0)]
    public string CompanyId
    {
        get
        {
            return this.companyIdField;
        }
        set
        {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=1)]
    public string DivisionId
    {
        get
        {
            return this.divisionIdField;
        }
        set
        {
            this.divisionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=2)]
    public string LabelId
    {
        get
        {
            return this.labelIdField;
        }
        set
        {
            this.labelIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class LocalLabelCopyMetadataType
{
    
    private string accountIdField;
    
    private OrgStructureType orgStructureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=0)]
    public string AccountId
    {
        get
        {
            return this.accountIdField;
        }
        set
        {
            this.accountIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public OrgStructureType OrgStructure
    {
        get
        {
            return this.orgStructureField;
        }
        set
        {
            this.orgStructureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class CountryType
{
    
    private string countryIdField;
    
    private string localReleaseDateField;
    
    private System.Nullable<System.DateTime> localExpiryDateField;
    
    private bool hasMarketingRestrictionField;
    
    private bool hasPreOrderField;
    
    private bool isPriorityField;
    
    private string releasingFamilyIdField;
    
    private LocalLabelCopyMetadataType localLabelCopyMetadataField;
    
    private string imprintField;
    
    private string projectCodeField;
    
    private string sourceField;
    
    private bool isReadyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CountryId
    {
        get
        {
            return this.countryIdField;
        }
        set
        {
            this.countryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string LocalReleaseDate
    {
        get
        {
            return this.localReleaseDateField;
        }
        set
        {
            this.localReleaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=2)]
    public System.Nullable<System.DateTime> LocalExpiryDate
    {
        get
        {
            return this.localExpiryDateField;
        }
        set
        {
            this.localExpiryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public bool HasMarketingRestriction
    {
        get
        {
            return this.hasMarketingRestrictionField;
        }
        set
        {
            this.hasMarketingRestrictionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public bool HasPreOrder
    {
        get
        {
            return this.hasPreOrderField;
        }
        set
        {
            this.hasPreOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public bool IsPriority
    {
        get
        {
            return this.isPriorityField;
        }
        set
        {
            this.isPriorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=6)]
    public string ReleasingFamilyId
    {
        get
        {
            return this.releasingFamilyIdField;
        }
        set
        {
            this.releasingFamilyIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public LocalLabelCopyMetadataType LocalLabelCopyMetadata
    {
        get
        {
            return this.localLabelCopyMetadataField;
        }
        set
        {
            this.localLabelCopyMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string Imprint
    {
        get
        {
            return this.imprintField;
        }
        set
        {
            this.imprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string ProjectCode
    {
        get
        {
            return this.projectCodeField;
        }
        set
        {
            this.projectCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string Source
    {
        get
        {
            return this.sourceField;
        }
        set
        {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public bool IsReady
    {
        get
        {
            return this.isReadyField;
        }
        set
        {
            this.isReadyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class ParentType
{
    
    private string parentUPCField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ParentUPC
    {
        get
        {
            return this.parentUPCField;
        }
        set
        {
            this.parentUPCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class ChildrenType
{
    
    private string[] childUPCField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChildUPC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string[] ChildUPC
    {
        get
        {
            return this.childUPCField;
        }
        set
        {
            this.childUPCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class MasterChildRelationshipType
{
    
    private bool isMasterField;
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public bool IsMaster
    {
        get
        {
            return this.isMasterField;
        }
        set
        {
            this.isMasterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Children", typeof(ChildrenType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("Parent", typeof(ParentType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class SecondaryManagementType
{
    
    private string regionField;
    
    private string releaseManagementField;
    
    private string[] countryIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string ReleaseManagement
    {
        get
        {
            return this.releaseManagementField;
        }
        set
        {
            this.releaseManagementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CountryId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string[] CountryId
    {
        get
        {
            return this.countryIdField;
        }
        set
        {
            this.countryIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/WSReleaseInformation/")]
public partial class ManagementType
{
    
    private string delegatedToField;
    
    private string releaseManagementField;
    
    private string[] countryIdField;
    
    private SecondaryManagementType[] secondaryManagementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string DelegatedTo
    {
        get
        {
            return this.delegatedToField;
        }
        set
        {
            this.delegatedToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string ReleaseManagement
    {
        get
        {
            return this.releaseManagementField;
        }
        set
        {
            this.releaseManagementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CountryId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string[] CountryId
    {
        get
        {
            return this.countryIdField;
        }
        set
        {
            this.countryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SecondaryManagement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public SecondaryManagementType[] SecondaryManagement
    {
        get
        {
            return this.secondaryManagementField;
        }
        set
        {
            this.secondaryManagementField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetFullRelease", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetFullReleaseRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UPC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string InternalReleaseId;
    
    public GetFullReleaseRequest()
    {
    }
    
    public GetFullReleaseRequest(string UPC, string InternalReleaseId)
    {
        this.UPC = UPC;
        this.InternalReleaseId = InternalReleaseId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetFullReleaseResponse", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetFullReleaseResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReleaseScheduleInformationType Release;
    
    public GetFullReleaseResponse()
    {
    }
    
    public GetFullReleaseResponse(ReleaseScheduleInformationType Release)
    {
        this.Release = Release;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReleaseWithoutWorkflow", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetReleaseWithoutWorkflowRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UPC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string InternalReleaseId;
    
    public GetReleaseWithoutWorkflowRequest()
    {
    }
    
    public GetReleaseWithoutWorkflowRequest(string UPC, string InternalReleaseId)
    {
        this.UPC = UPC;
        this.InternalReleaseId = InternalReleaseId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReleaseWithoutWorkflowResponse", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetReleaseWithoutWorkflowResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReleaseScheduleInformationType Release;
    
    public GetReleaseWithoutWorkflowResponse()
    {
    }
    
    public GetReleaseWithoutWorkflowResponse(ReleaseScheduleInformationType Release)
    {
        this.Release = Release;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReleaseWithoutMasterChild", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetReleaseWithoutMasterChildRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UPC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string InternalReleaseId;
    
    public GetReleaseWithoutMasterChildRequest()
    {
    }
    
    public GetReleaseWithoutMasterChildRequest(string UPC, string InternalReleaseId)
    {
        this.UPC = UPC;
        this.InternalReleaseId = InternalReleaseId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReleaseWithoutMasterChildResponse", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetReleaseWithoutMasterChildResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReleaseScheduleInformationType Release;
    
    public GetReleaseWithoutMasterChildResponse()
    {
    }
    
    public GetReleaseWithoutMasterChildResponse(ReleaseScheduleInformationType Release)
    {
        this.Release = Release;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReleaseWithoutMasterChildAndWorkflow", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetReleaseWithoutMasterChildAndWorkflowRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UPC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string InternalReleaseId;
    
    public GetReleaseWithoutMasterChildAndWorkflowRequest()
    {
    }
    
    public GetReleaseWithoutMasterChildAndWorkflowRequest(string UPC, string InternalReleaseId)
    {
        this.UPC = UPC;
        this.InternalReleaseId = InternalReleaseId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReleaseWithoutMasterChildAndWorkflowResponse", WrapperNamespace="http://www.example.org/WSReleaseInformation/", IsWrapped=true)]
public partial class GetReleaseWithoutMasterChildAndWorkflowResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/WSReleaseInformation/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReleaseScheduleInformationType Release;
    
    public GetReleaseWithoutMasterChildAndWorkflowResponse()
    {
    }
    
    public GetReleaseWithoutMasterChildAndWorkflowResponse(ReleaseScheduleInformationType Release)
    {
        this.Release = Release;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface WSReleaseInformationChannel : WSReleaseInformation, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WSReleaseInformationClient : System.ServiceModel.ClientBase<WSReleaseInformation>, WSReleaseInformation
{
    
    public WSReleaseInformationClient()
    {
    }
    
    public WSReleaseInformationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WSReleaseInformationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WSReleaseInformationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WSReleaseInformationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetFullReleaseResponse WSReleaseInformation.GetFullRelease(GetFullReleaseRequest request)
    {
        return base.Channel.GetFullRelease(request);
    }
    
    public ReleaseScheduleInformationType GetFullRelease(string UPC, string InternalReleaseId)
    {
        GetFullReleaseRequest inValue = new GetFullReleaseRequest();
        inValue.UPC = UPC;
        inValue.InternalReleaseId = InternalReleaseId;
        GetFullReleaseResponse retVal = ((WSReleaseInformation)(this)).GetFullRelease(inValue);
        return retVal.Release;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetReleaseWithoutWorkflowResponse WSReleaseInformation.GetReleaseWithoutWorkflow(GetReleaseWithoutWorkflowRequest request)
    {
        return base.Channel.GetReleaseWithoutWorkflow(request);
    }
    
    public ReleaseScheduleInformationType GetReleaseWithoutWorkflow(string UPC, string InternalReleaseId)
    {
        GetReleaseWithoutWorkflowRequest inValue = new GetReleaseWithoutWorkflowRequest();
        inValue.UPC = UPC;
        inValue.InternalReleaseId = InternalReleaseId;
        GetReleaseWithoutWorkflowResponse retVal = ((WSReleaseInformation)(this)).GetReleaseWithoutWorkflow(inValue);
        return retVal.Release;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetReleaseWithoutMasterChildResponse WSReleaseInformation.GetReleaseWithoutMasterChild(GetReleaseWithoutMasterChildRequest request)
    {
        return base.Channel.GetReleaseWithoutMasterChild(request);
    }
    
    public ReleaseScheduleInformationType GetReleaseWithoutMasterChild(string UPC, string InternalReleaseId)
    {
        GetReleaseWithoutMasterChildRequest inValue = new GetReleaseWithoutMasterChildRequest();
        inValue.UPC = UPC;
        inValue.InternalReleaseId = InternalReleaseId;
        GetReleaseWithoutMasterChildResponse retVal = ((WSReleaseInformation)(this)).GetReleaseWithoutMasterChild(inValue);
        return retVal.Release;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetReleaseWithoutMasterChildAndWorkflowResponse WSReleaseInformation.GetReleaseWithoutMasterChildAndWorkflow(GetReleaseWithoutMasterChildAndWorkflowRequest request)
    {
        return base.Channel.GetReleaseWithoutMasterChildAndWorkflow(request);
    }
    
    public ReleaseScheduleInformationType GetReleaseWithoutMasterChildAndWorkflow(string UPC, string InternalReleaseId)
    {
        GetReleaseWithoutMasterChildAndWorkflowRequest inValue = new GetReleaseWithoutMasterChildAndWorkflowRequest();
        inValue.UPC = UPC;
        inValue.InternalReleaseId = InternalReleaseId;
        GetReleaseWithoutMasterChildAndWorkflowResponse retVal = ((WSReleaseInformation)(this)).GetReleaseWithoutMasterChildAndWorkflow(inValue);
        return retVal.Release;
    }
}
