//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace UMGI.GRCS.BusinessEntities.Entities.NotificationEntities
{
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.umusic.com", IsNullable = false)]
    public partial class ClrProject
    {

        private ClrProjectProjectInformation projectInformationField;

        private ClrProjectThirdParty thirdPartyField;

        private ClrProjectRequestDetails requestDetailsField;

        /// <remarks/>
        [DataMember]
        public ClrProjectProjectInformation ProjectInformation
        {
            get
            {
                return this.projectInformationField;
            }
            set
            {
                this.projectInformationField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public ClrProjectThirdParty ThirdParty
        {
            get
            {
                return this.thirdPartyField;
            }
            set
            {
                this.thirdPartyField = value;
            }
        }

        /// <remarks/>
        [DataMember]
        public ClrProjectRequestDetails RequestDetails
        {
            get
            {
                return this.requestDetailsField;
            }
            set
            {
                this.requestDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectProjectInformation
    {

        private string projectReferenceField;

        private string projectTypeField;

        private System.DateTime createdDateField;

        private string projectTitleField;

        private string localReferenceField;

        private string requestingCompanyIDField;

        private string statusField;

        private string currencyField;

        private bool sensitiveExploitationFlagField;

        private bool sensitiveExploitationFlagFieldSpecified;

        private string[] releaseTerritoriesField;

        private string estimatedSalesOrUnitsField;

        private System.DateTime releaseDateField;

        private bool releaseDateFieldSpecified;

        private bool multiArtistFlagField;

        private bool multiArtistFlagFieldSpecified;

        private bool compilationFlagField;

        private bool compilationFlagFieldSpecified;

        private bool highPriorityField;

        private bool highPriorityFieldSpecified;

        /// <remarks/>
        public string ProjectReference
        {
            get
            {
                return this.projectReferenceField;
            }
            set
            {
                this.projectReferenceField = value;
            }
        }

        /// <remarks/>
        public string ProjectType
        {
            get
            {
                return this.projectTypeField;
            }
            set
            {
                this.projectTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public string ProjectTitle
        {
            get
            {
                return this.projectTitleField;
            }
            set
            {
                this.projectTitleField = value;
            }
        }

        /// <remarks/>
        public string LocalReference
        {
            get
            {
                return this.localReferenceField;
            }
            set
            {
                this.localReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string RequestingCompanyID
        {
            get
            {
                return this.requestingCompanyIDField;
            }
            set
            {
                this.requestingCompanyIDField = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        public bool SensitiveExploitationFlag
        {
            get
            {
                return this.sensitiveExploitationFlagField;
            }
            set
            {
                this.sensitiveExploitationFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SensitiveExploitationFlagSpecified
        {
            get
            {
                return this.sensitiveExploitationFlagFieldSpecified;
            }
            set
            {
                this.sensitiveExploitationFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CountryCode", IsNullable = false)]
        public string[] ReleaseTerritories
        {
            get
            {
                return this.releaseTerritoriesField;
            }
            set
            {
                this.releaseTerritoriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string EstimatedSalesOrUnits
        {
            get
            {
                return this.estimatedSalesOrUnitsField;
            }
            set
            {
                this.estimatedSalesOrUnitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ReleaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleaseDateSpecified
        {
            get
            {
                return this.releaseDateFieldSpecified;
            }
            set
            {
                this.releaseDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool MultiArtistFlag
        {
            get
            {
                return this.multiArtistFlagField;
            }
            set
            {
                this.multiArtistFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultiArtistFlagSpecified
        {
            get
            {
                return this.multiArtistFlagFieldSpecified;
            }
            set
            {
                this.multiArtistFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool CompilationFlag
        {
            get
            {
                return this.compilationFlagField;
            }
            set
            {
                this.compilationFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompilationFlagSpecified
        {
            get
            {
                return this.compilationFlagFieldSpecified;
            }
            set
            {
                this.compilationFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HighPriority
        {
            get
            {
                return this.highPriorityField;
            }
            set
            {
                this.highPriorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighPrioritySpecified
        {
            get
            {
                return this.highPriorityFieldSpecified;
            }
            set
            {
                this.highPriorityFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectThirdParty
    {

        private string licenseTermField;

        private bool thirdPartyFlagField;

        private bool thirdPartyFlagFieldSpecified;

        private string thirdPartyCompanyField;

        private string thirdPartyCountryField;

        /// <remarks/>
        public string LicenseTerm
        {
            get
            {
                return this.licenseTermField;
            }
            set
            {
                this.licenseTermField = value;
            }
        }

        /// <remarks/>
        public bool ThirdPartyFlag
        {
            get
            {
                return this.thirdPartyFlagField;
            }
            set
            {
                this.thirdPartyFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThirdPartyFlagSpecified
        {
            get
            {
                return this.thirdPartyFlagFieldSpecified;
            }
            set
            {
                this.thirdPartyFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ThirdPartyCompany
        {
            get
            {
                return this.thirdPartyCompanyField;
            }
            set
            {
                this.thirdPartyCompanyField = value;
            }
        }

        /// <remarks/>
        public string ThirdPartyCountry
        {
            get
            {
                return this.thirdPartyCountryField;
            }
            set
            {
                this.thirdPartyCountryField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetails
    {

        private string clientNameField;

        private ClrProjectRequestDetailsAdvertising advertisingField;

        private ClrProjectRequestDetailsFilm filmField;

        private ClrProjectRequestDetailsTrailer trailerField;

        private ClrProjectRequestDetailsOthers othersField;

        private string scopeFlagField;

        private string releaseTypeField;

        private string regularRetailField;

        private ClrProjectRequestDetailsClub clubField;

        private ClrProjectRequestDetailsNonTradition nonTraditionField;

        private string promotionalField;

        private ClrProjectRequestDetailsTVRadioBreakICLA tVRadioBreakICLAField;

        private ClrProjectRequestDetailsPriceReduction priceReductionField;

        /// <remarks/>
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsAdvertising Advertising
        {
            get
            {
                return this.advertisingField;
            }
            set
            {
                this.advertisingField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsFilm Film
        {
            get
            {
                return this.filmField;
            }
            set
            {
                this.filmField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsTrailer Trailer
        {
            get
            {
                return this.trailerField;
            }
            set
            {
                this.trailerField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsOthers Others
        {
            get
            {
                return this.othersField;
            }
            set
            {
                this.othersField = value;
            }
        }

        /// <remarks/>
        public string ScopeFlag
        {
            get
            {
                return this.scopeFlagField;
            }
            set
            {
                this.scopeFlagField = value;
            }
        }

        /// <remarks/>
        public string ReleaseType
        {
            get
            {
                return this.releaseTypeField;
            }
            set
            {
                this.releaseTypeField = value;
            }
        }

        /// <remarks/>
        public string RegularRetail
        {
            get
            {
                return this.regularRetailField;
            }
            set
            {
                this.regularRetailField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsClub Club
        {
            get
            {
                return this.clubField;
            }
            set
            {
                this.clubField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsNonTradition NonTradition
        {
            get
            {
                return this.nonTraditionField;
            }
            set
            {
                this.nonTraditionField = value;
            }
        }

        /// <remarks/>
        public string Promotional
        {
            get
            {
                return this.promotionalField;
            }
            set
            {
                this.promotionalField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsTVRadioBreakICLA TVRadioBreakICLA
        {
            get
            {
                return this.tVRadioBreakICLAField;
            }
            set
            {
                this.tVRadioBreakICLAField = value;
            }
        }

        /// <remarks/>
        public ClrProjectRequestDetailsPriceReduction PriceReduction
        {
            get
            {
                return this.priceReductionField;
            }
            set
            {
                this.priceReductionField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsAdvertising
    {

        private string[] mediaTypeField;

        private string initialNoOfVideosField;

        private System.DateTime durationFromField;

        private bool durationFromFieldSpecified;

        private System.DateTime durationToField;

        private bool durationToFieldSpecified;

        private string numberOfSpotsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MediaType")]
        public string[] MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string InitialNoOfVideos
        {
            get
            {
                return this.initialNoOfVideosField;
            }
            set
            {
                this.initialNoOfVideosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DurationFrom
        {
            get
            {
                return this.durationFromField;
            }
            set
            {
                this.durationFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurationFromSpecified
        {
            get
            {
                return this.durationFromFieldSpecified;
            }
            set
            {
                this.durationFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DurationTo
        {
            get
            {
                return this.durationToField;
            }
            set
            {
                this.durationToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurationToSpecified
        {
            get
            {
                return this.durationToFieldSpecified;
            }
            set
            {
                this.durationToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string NumberOfSpots
        {
            get
            {
                return this.numberOfSpotsField;
            }
            set
            {
                this.numberOfSpotsField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsFilm
    {

        private string[] mediaTypeField;

        private string initialNoOfVideosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MediaType")]
        public string[] MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string InitialNoOfVideos
        {
            get
            {
                return this.initialNoOfVideosField;
            }
            set
            {
                this.initialNoOfVideosField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsTrailer
    {

        private string[] mediaTypeField;

        private string initialNoOfVideosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MediaType")]
        public string[] MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string InitialNoOfVideos
        {
            get
            {
                return this.initialNoOfVideosField;
            }
            set
            {
                this.initialNoOfVideosField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsOthers
    {

        private string[] mediaTypeField;

        private string initialNoOfVideosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MediaType")]
        public string[] MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string InitialNoOfVideos
        {
            get
            {
                return this.initialNoOfVideosField;
            }
            set
            {
                this.initialNoOfVideosField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsClub
    {

        private bool additionalClubField;

        private bool additionalClubFieldSpecified;

        private bool introductoryUseField;

        private bool introductoryUseFieldSpecified;

        /// <remarks/>
        public bool AdditionalClub
        {
            get
            {
                return this.additionalClubField;
            }
            set
            {
                this.additionalClubField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalClubSpecified
        {
            get
            {
                return this.additionalClubFieldSpecified;
            }
            set
            {
                this.additionalClubFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool IntroductoryUse
        {
            get
            {
                return this.introductoryUseField;
            }
            set
            {
                this.introductoryUseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntroductoryUseSpecified
        {
            get
            {
                return this.introductoryUseFieldSpecified;
            }
            set
            {
                this.introductoryUseFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsNonTradition
    {

        private bool manufacturedByUMGField;

        private bool manufacturedByUMGFieldSpecified;

        private bool partworkField;

        private bool partworkFieldSpecified;

        private bool kioskField;

        private bool kioskFieldSpecified;

        private bool mailOrderField;

        private bool mailOrderFieldSpecified;

        private bool internetField;

        private bool internetFieldSpecified;

        private bool directResponseField;

        private bool directResponseFieldSpecified;

        private bool educationalField;

        private bool educationalFieldSpecified;

        private bool giveAwayFOCField;

        private bool giveAwayFOCFieldSpecified;

        private bool premiumField;

        private bool premiumFieldSpecified;

        private bool otherField;

        private bool otherFieldSpecified;

        /// <remarks/>
        public bool ManufacturedByUMG
        {
            get
            {
                return this.manufacturedByUMGField;
            }
            set
            {
                this.manufacturedByUMGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ManufacturedByUMGSpecified
        {
            get
            {
                return this.manufacturedByUMGFieldSpecified;
            }
            set
            {
                this.manufacturedByUMGFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Partwork
        {
            get
            {
                return this.partworkField;
            }
            set
            {
                this.partworkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartworkSpecified
        {
            get
            {
                return this.partworkFieldSpecified;
            }
            set
            {
                this.partworkFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Kiosk
        {
            get
            {
                return this.kioskField;
            }
            set
            {
                this.kioskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KioskSpecified
        {
            get
            {
                return this.kioskFieldSpecified;
            }
            set
            {
                this.kioskFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool MailOrder
        {
            get
            {
                return this.mailOrderField;
            }
            set
            {
                this.mailOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MailOrderSpecified
        {
            get
            {
                return this.mailOrderFieldSpecified;
            }
            set
            {
                this.mailOrderFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Internet
        {
            get
            {
                return this.internetField;
            }
            set
            {
                this.internetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternetSpecified
        {
            get
            {
                return this.internetFieldSpecified;
            }
            set
            {
                this.internetFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool DirectResponse
        {
            get
            {
                return this.directResponseField;
            }
            set
            {
                this.directResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectResponseSpecified
        {
            get
            {
                return this.directResponseFieldSpecified;
            }
            set
            {
                this.directResponseFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Educational
        {
            get
            {
                return this.educationalField;
            }
            set
            {
                this.educationalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EducationalSpecified
        {
            get
            {
                return this.educationalFieldSpecified;
            }
            set
            {
                this.educationalFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool GiveAwayFOC
        {
            get
            {
                return this.giveAwayFOCField;
            }
            set
            {
                this.giveAwayFOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GiveAwayFOCSpecified
        {
            get
            {
                return this.giveAwayFOCFieldSpecified;
            }
            set
            {
                this.giveAwayFOCFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Premium
        {
            get
            {
                return this.premiumField;
            }
            set
            {
                this.premiumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumSpecified
        {
            get
            {
                return this.premiumFieldSpecified;
            }
            set
            {
                this.premiumFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Other
        {
            get
            {
                return this.otherField;
            }
            set
            {
                this.otherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherSpecified
        {
            get
            {
                return this.otherFieldSpecified;
            }
            set
            {
                this.otherFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsTVRadioBreakICLA
    {

        private bool tVRadioOthersField;

        private bool tVRadioOthersFieldSpecified;

        private ClrProjectRequestDetailsTVRadioBreakICLATVRadioOtherBudget[] tVRadioOtherBudgetField;

        private string salesChannelField;

        private string physicalSplitSalesToDateField;

        private string physicalSplitSalesWithField;

        private string physicalSplitSalesWithoutField;

        private string digitalSplitSalesDateField;

        private string digitalSplitSalesWithField;

        private string digitalSplitSalesWithoutField;

        private string totalSplitSalesToDateField;

        private string totalSplitSalesWithField;

        private string totalSplitSalesWithoutField;

        private string physicalRevenueSplitToDateField;

        private string physicalRevenueSplitWithField;

        private string physicalRevenueSplitWithoutField;

        private string digitalRevenueSplitToDateField;

        private string digitalRevenueSplitWithField;

        private string digitalRevenueSplitWithoutField;

        private string totalRevenueSplitToDateField;

        private string totalRevenueSplitWithField;

        private string totalRevenueSplitWithoutField;

        private string[] campaignTerritoriesIncludeExcludeField;

        /// <remarks/>
        public bool TVRadioOthers
        {
            get
            {
                return this.tVRadioOthersField;
            }
            set
            {
                this.tVRadioOthersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TVRadioOthersSpecified
        {
            get
            {
                return this.tVRadioOthersFieldSpecified;
            }
            set
            {
                this.tVRadioOthersFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TVRadioOtherBudget")]
        public ClrProjectRequestDetailsTVRadioBreakICLATVRadioOtherBudget[] TVRadioOtherBudget
        {
            get
            {
                return this.tVRadioOtherBudgetField;
            }
            set
            {
                this.tVRadioOtherBudgetField = value;
            }
        }

        /// <remarks/>
        public string SalesChannel
        {
            get
            {
                return this.salesChannelField;
            }
            set
            {
                this.salesChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PhysicalSplitSalesToDate
        {
            get
            {
                return this.physicalSplitSalesToDateField;
            }
            set
            {
                this.physicalSplitSalesToDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PhysicalSplitSalesWith
        {
            get
            {
                return this.physicalSplitSalesWithField;
            }
            set
            {
                this.physicalSplitSalesWithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PhysicalSplitSalesWithout
        {
            get
            {
                return this.physicalSplitSalesWithoutField;
            }
            set
            {
                this.physicalSplitSalesWithoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DigitalSplitSalesDate
        {
            get
            {
                return this.digitalSplitSalesDateField;
            }
            set
            {
                this.digitalSplitSalesDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DigitalSplitSalesWith
        {
            get
            {
                return this.digitalSplitSalesWithField;
            }
            set
            {
                this.digitalSplitSalesWithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DigitalSplitSalesWithout
        {
            get
            {
                return this.digitalSplitSalesWithoutField;
            }
            set
            {
                this.digitalSplitSalesWithoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalSplitSalesToDate
        {
            get
            {
                return this.totalSplitSalesToDateField;
            }
            set
            {
                this.totalSplitSalesToDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalSplitSalesWith
        {
            get
            {
                return this.totalSplitSalesWithField;
            }
            set
            {
                this.totalSplitSalesWithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalSplitSalesWithout
        {
            get
            {
                return this.totalSplitSalesWithoutField;
            }
            set
            {
                this.totalSplitSalesWithoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PhysicalRevenueSplitToDate
        {
            get
            {
                return this.physicalRevenueSplitToDateField;
            }
            set
            {
                this.physicalRevenueSplitToDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PhysicalRevenueSplitWith
        {
            get
            {
                return this.physicalRevenueSplitWithField;
            }
            set
            {
                this.physicalRevenueSplitWithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string PhysicalRevenueSplitWithout
        {
            get
            {
                return this.physicalRevenueSplitWithoutField;
            }
            set
            {
                this.physicalRevenueSplitWithoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DigitalRevenueSplitToDate
        {
            get
            {
                return this.digitalRevenueSplitToDateField;
            }
            set
            {
                this.digitalRevenueSplitToDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DigitalRevenueSplitWith
        {
            get
            {
                return this.digitalRevenueSplitWithField;
            }
            set
            {
                this.digitalRevenueSplitWithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DigitalRevenueSplitWithout
        {
            get
            {
                return this.digitalRevenueSplitWithoutField;
            }
            set
            {
                this.digitalRevenueSplitWithoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalRevenueSplitToDate
        {
            get
            {
                return this.totalRevenueSplitToDateField;
            }
            set
            {
                this.totalRevenueSplitToDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalRevenueSplitWith
        {
            get
            {
                return this.totalRevenueSplitWithField;
            }
            set
            {
                this.totalRevenueSplitWithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalRevenueSplitWithout
        {
            get
            {
                return this.totalRevenueSplitWithoutField;
            }
            set
            {
                this.totalRevenueSplitWithoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CountryCode", IsNullable = false)]
        public string[] CampaignTerritoriesIncludeExclude
        {
            get
            {
                return this.campaignTerritoriesIncludeExcludeField;
            }
            set
            {
                this.campaignTerritoriesIncludeExcludeField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsTVRadioBreakICLATVRadioOtherBudget
    {

        private string mediaTypeField;

        private string budgetField;

        private string budgetInUSDField;

        private string productionCostOfCommercialField;

        /// <remarks/>
        public string MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Budget
        {
            get
            {
                return this.budgetField;
            }
            set
            {
                this.budgetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string BudgetInUSD
        {
            get
            {
                return this.budgetInUSDField;
            }
            set
            {
                this.budgetInUSDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ProductionCostOfCommercial
        {
            get
            {
                return this.productionCostOfCommercialField;
            }
            set
            {
                this.productionCostOfCommercialField = value;
            }
        }
    }

    /// <remarks/>
    [DataContract]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.umusic.com")]
    public partial class ClrProjectRequestDetailsPriceReduction
    {

        private string currentPriceLevelField;

        private string requestedPriceLevelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string CurrentPriceLevel
        {
            get
            {
                return this.currentPriceLevelField;
            }
            set
            {
                this.currentPriceLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string RequestedPriceLevel
        {
            get
            {
                return this.requestedPriceLevelField;
            }
            set
            {
                this.requestedPriceLevelField = value;
            }
        }
    }

}