//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMGI.GRCS.Resx.Resource.UIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RepertoireSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepertoireSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMGI.GRCS.Resx.Resource.UIResources.RepertoireSearch", typeof(RepertoireSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active for Marketing.
        /// </summary>
        public static string ActiveForMarketing {
            get {
                return ResourceManager.GetString("ActiveForMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Restriction Parameter.
        /// </summary>
        public static string AddRestrictionParameterHeading {
            get {
                return ResourceManager.GetString("AddRestrictionParameterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advert Royalty Breaks.
        /// </summary>
        public static string AdvertRoyaltyBreaks {
            get {
                return ResourceManager.GetString("AdvertRoyaltyBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;sampleArtist&apos; title=&apos;Side Artist&apos; /&gt;.
        /// </summary>
        public static string ArtistImage {
            get {
                return ResourceManager.GetString("ArtistImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Name.
        /// </summary>
        public static string ArtistName {
            get {
                return ResourceManager.GetString("ArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Search.
        /// </summary>
        public static string BasicSearchHeading {
            get {
                return ResourceManager.GetString("BasicSearchHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Compilation.
        /// </summary>
        public static string BudgetCompilation {
            get {
                return ResourceManager.GetString("BudgetCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;sampleExists&apos; title=&apos;Sample Exists&apos;/&gt;.
        /// </summary>
        public static string CdImage {
            get {
                return ResourceManager.GetString("CdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance/Data Admin Co..
        /// </summary>
        public static string ClearanceOrDataAdminCompany {
            get {
                return ResourceManager.GetString("ClearanceOrDataAdminCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Mail Order.
        /// </summary>
        public static string ClubMailOrder {
            get {
                return ResourceManager.GetString("ClubMailOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Models.
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Models.
        /// </summary>
        public static string CommercialModels {
            get {
                return ResourceManager.GetString("CommercialModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm to reset the values.
        /// </summary>
        public static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent/Consult Period.
        /// </summary>
        public static string ConsentPeriod {
            get {
                return ResourceManager.GetString("ConsentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a &apos;To&apos; date later than the &apos;From&apos; date.
        /// </summary>
        public static string DateValidation {
            get {
                return ResourceManager.GetString("DateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date should not be Equal to From Date.
        /// </summary>
        public static string DateValidationEqual {
            get {
                return ResourceManager.GetString("DateValidationEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Digital {
            get {
                return ResourceManager.GetString("Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Exploitation.
        /// </summary>
        public static string DigitalExploitation {
            get {
                return ResourceManager.GetString("DigitalExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Exploitation Rights.
        /// </summary>
        public static string DigitalExploitationRights {
            get {
                return ResourceManager.GetString("DigitalExploitationRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Restrictions.
        /// </summary>
        public static string DigitalRestrictionsHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsReleases.
        /// </summary>
        public static string DigitalRestrictionsReleases {
            get {
                return ResourceManager.GetString("DigitalRestrictionsReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/.
        /// </summary>
        public static string DigitalRestrictionsReleasesPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsReleasesPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsResourcesAndTracksBasicSearch.
        /// </summary>
        public static string DigitalRestrictionsResourcesAndTracksBasicSearch {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesAndTracksBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/Show Resources &amp; Tracks/.
        /// </summary>
        public static string DigitalRestrictionsResourcesAndTracksBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesAndTracksBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsResourcesAndTracksSearchReleaseParameters.
        /// </summary>
        public static string DigitalRestrictionsResourcesAndTracksSearchReleaseParameters {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesAndTracksSearchReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/Show Resources &amp; Tracks/.
        /// </summary>
        public static string DigitalRestrictionsResourcesAndTracksSearchReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesAndTracksSearchReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsResourcesBasicSearch.
        /// </summary>
        public static string DigitalRestrictionsResourcesBasicSearch {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/Show Resources/.
        /// </summary>
        public static string DigitalRestrictionsResourcesBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsResourcesReleaseParameters.
        /// </summary>
        public static string DigitalRestrictionsResourcesReleaseParameters {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/Show Resources/.
        /// </summary>
        public static string DigitalRestrictionsResourcesReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsResourcesReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsTracksBasicSearch.
        /// </summary>
        public static string DigitalRestrictionsTracksBasicSearch {
            get {
                return ResourceManager.GetString("DigitalRestrictionsTracksBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/Show Tracks/.
        /// </summary>
        public static string DigitalRestrictionsTracksBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsTracksBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalRestrictionsTracksSearchReleaseParameters.
        /// </summary>
        public static string DigitalRestrictionsTracksSearchReleaseParameters {
            get {
                return ResourceManager.GetString("DigitalRestrictionsTracksSearchReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/Show Tracks/.
        /// </summary>
        public static string DigitalRestrictionsTracksSearchReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("DigitalRestrictionsTracksSearchReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Unbundling Allowed.
        /// </summary>
        public static string DigitalUnbundlingAllowed {
            get {
                return ResourceManager.GetString("DigitalUnbundlingAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Marketing.
        /// </summary>
        public static string DirectMarketing {
            get {
                return ResourceManager.GetString("DirectMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Search.
        /// </summary>
        public static string ExactSearch {
            get {
                return ResourceManager.GetString("ExactSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Report.
        /// </summary>
        public static string ExportReport {
            get {
                return ResourceManager.GetString("ExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is empty. Please upload a non empty Microsoft Excel 2010/2007/2003 file..
        /// </summary>
        public static string fileEmptyMsg {
            get {
                return ResourceManager.GetString("fileEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights data doesn&apos;t exist in system for one/more item(s) uploaded.
        /// </summary>
        public static string FileUploadMsgTitle {
            get {
                return ResourceManager.GetString("FileUploadMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format not recognised. Please upload Microsoft Excel 2010/2007/2003 file types only.
        /// </summary>
        public static string fileValidation {
            get {
                return ResourceManager.GetString("fileValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrcsUtilityService.
        /// </summary>
        public static string GrcsUtilityService {
            get {
                return ResourceManager.GetString("GrcsUtilityService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatest Hits.
        /// </summary>
        public static string GreatestHits {
            get {
                return ResourceManager.GetString("GreatestHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to view Sensitive Rights information. Please select a past date in the ‘To’ date’ field if no search results are displayed.
        /// </summary>
        public static string InsufficientPrivilege {
            get {
                return ResourceManager.GetString("InsufficientPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRC.
        /// </summary>
        public static string ISRC {
            get {
                return ResourceManager.GetString("ISRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items per page.
        /// </summary>
        public static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk.
        /// </summary>
        public static string Kiosk {
            get {
                return ResourceManager.GetString("Kiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Contract Name.
        /// </summary>
        public static string LinkedContactName {
            get {
                return ResourceManager.GetString("LinkedContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Contract.
        /// </summary>
        public static string LinkedContract {
            get {
                return ResourceManager.GetString("LinkedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Rights.
        /// </summary>
        public static string LostRights {
            get {
                return ResourceManager.GetString("LostRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Rights Date.
        /// </summary>
        public static string LostRightsDate {
            get {
                return ResourceManager.GetString("LostRightsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Rights Indicator.
        /// </summary>
        public static string LostRightsIndicator {
            get {
                return ResourceManager.GetString("LostRightsIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Rights Reason.
        /// </summary>
        public static string LostRightsReason {
            get {
                return ResourceManager.GetString("LostRightsReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master/Synchronization Use.
        /// </summary>
        public static string MasterOrSynchronizationUse {
            get {
                return ResourceManager.GetString("MasterOrSynchronizationUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Price.
        /// </summary>
        public static string MidPrice {
            get {
                return ResourceManager.GetString("MidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Price Compilation.
        /// </summary>
        public static string MidPriceCompilation {
            get {
                return ResourceManager.GetString("MidPriceCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Exploitation.
        /// </summary>
        public static string MobileExploitation {
            get {
                return ResourceManager.GetString("MobileExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Exploitation Rights.
        /// </summary>
        public static string MobileExploitationRights {
            get {
                return ResourceManager.GetString("MobileExploitationRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Artist Compilation.
        /// </summary>
        public static string MultiArtistCompilation {
            get {
                return ResourceManager.GetString("MultiArtistCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change Required.
        /// </summary>
        public static string NoChangeRequired {
            get {
                return ResourceManager.GetString("NoChangeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Exploitation.
        /// </summary>
        public static string PhysicalExploitation {
            get {
                return ResourceManager.GetString("PhysicalExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Exploitation Rights.
        /// </summary>
        public static string PhysicalExploitationRights {
            get {
                return ResourceManager.GetString("PhysicalExploitationRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPB Revenue Claim.
        /// </summary>
        public static string PPBRevenueClaim {
            get {
                return ResourceManager.GetString("PPBRevenueClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Clearance.
        /// </summary>
        public static string PreClearanceHeading {
            get {
                return ResourceManager.GetString("PreClearanceHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-ClearanceTerritory Exclusions.
        /// </summary>
        public static string PreClearanceTerritoryExclusions {
            get {
                return ResourceManager.GetString("PreClearanceTerritoryExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Clearance Types.
        /// </summary>
        public static string PreClearanceTypes {
            get {
                return ResourceManager.GetString("PreClearanceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pre-Clearance Types available!.
        /// </summary>
        public static string PreClearanceTypesNotAvailable {
            get {
                return ResourceManager.GetString("PreClearanceTypesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Clearance .
        /// </summary>
        public static string PreCleared {
            get {
                return ResourceManager.GetString("PreCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreClearedBasicSearch.
        /// </summary>
        public static string PreClearedBasicSearch {
            get {
                return ResourceManager.GetString("PreClearedBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Pre-Cleared/.
        /// </summary>
        public static string PreClearedBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("PreClearedBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreClearedReleaseParameters.
        /// </summary>
        public static string PreClearedReleaseParameters {
            get {
                return ResourceManager.GetString("PreClearedReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Pre-Cleared/.
        /// </summary>
        public static string PreClearedReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("PreClearedReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiums.
        /// </summary>
        public static string Premiums {
            get {
                return ResourceManager.GetString("Premiums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P Year.
        /// </summary>
        public static string Pyear {
            get {
                return ResourceManager.GetString("Pyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Parameters.
        /// </summary>
        public static string ReleaseParameters {
            get {
                return ResourceManager.GetString("ReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseService.
        /// </summary>
        public static string ReleaseService {
            get {
                return ResourceManager.GetString("ReleaseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/.
        /// </summary>
        public static string ReleasesPageHeading {
            get {
                return ResourceManager.GetString("ReleasesPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Title.
        /// </summary>
        public static string ReleaseTitle {
            get {
                return ResourceManager.GetString("ReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remix/Edit.
        /// </summary>
        public static string RemixEdits {
            get {
                return ResourceManager.GetString("RemixEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire linked to multiple contracts.
        /// </summary>
        public static string RepertoireLinkedToMultipleContracts {
            get {
                return ResourceManager.GetString("RepertoireLinkedToMultipleContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Parameters.
        /// </summary>
        public static string ResourceParameters {
            get {
                return ResourceManager.GetString("ResourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesAndTracksBasicSearch.
        /// </summary>
        public static string ResourcesAndTracksBasicSearch {
            get {
                return ResourceManager.GetString("ResourcesAndTracksBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights/Show Resources &amp; Track/.
        /// </summary>
        public static string ResourcesAndTracksBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("ResourcesAndTracksBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesAndTracksSearchReleaseParameters.
        /// </summary>
        public static string ResourcesAndTracksSearchReleaseParameters {
            get {
                return ResourceManager.GetString("ResourcesAndTracksSearchReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights/Show Resources &amp; Tracks/.
        /// </summary>
        public static string ResourcesAndTracksSearchReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("ResourcesAndTracksSearchReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesBasicSearch.
        /// </summary>
        public static string ResourcesBasicSearch {
            get {
                return ResourceManager.GetString("ResourcesBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights/Show Resources/.
        /// </summary>
        public static string ResourcesBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("ResourcesBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceService.
        /// </summary>
        public static string ResourceService {
            get {
                return ResourceManager.GetString("ResourceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesReleaseParameters.
        /// </summary>
        public static string ResourcesReleaseParameters {
            get {
                return ResourceManager.GetString("ResourcesReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights/Show Resources/.
        /// </summary>
        public static string ResourcesReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("ResourcesReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource&apos;s Rights Parameter.
        /// </summary>
        public static string ResourcesRightsParameter {
            get {
                return ResourceManager.GetString("ResourcesRightsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource&apos;s &amp; Track&apos;s Rights Parameter.
        /// </summary>
        public static string ResourcesTracksRightsParameterHeading {
            get {
                return ResourceManager.GetString("ResourcesTracksRightsParameterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Title.
        /// </summary>
        public static string ResourceTitle {
            get {
                return ResourceManager.GetString("ResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource/TrackTitle.
        /// </summary>
        public static string ResourceTrackTitle {
            get {
                return ResourceManager.GetString("ResourceTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        public static string ResourceType {
            get {
                return ResourceManager.GetString("ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction Reason.
        /// </summary>
        public static string RestrictionReason {
            get {
                return ResourceManager.GetString("RestrictionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to remove all matching Digital Restrictions from the selected Repertoire.
        /// </summary>
        public static string RestrictionRemoveMessage {
            get {
                return ResourceManager.GetString("RestrictionRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction Removal-Confirmation.
        /// </summary>
        public static string RestrictionRemoveTitle {
            get {
                return ResourceManager.GetString("RestrictionRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Restrictions {
            get {
                return ResourceManager.GetString("Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions Doesn&apos;t Exists.
        /// </summary>
        public static string RestrictionsDoesntExists {
            get {
                return ResourceManager.GetString("RestrictionsDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions Exists.
        /// </summary>
        public static string RestrictionsExists {
            get {
                return ResourceManager.GetString("RestrictionsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Rights.
        /// </summary>
        public static string ReviewRightsButton {
            get {
                return ResourceManager.GetString("ReviewRightsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Status.
        /// </summary>
        public static string ReviewStatus {
            get {
                return ResourceManager.GetString("ReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights Acquired.
        /// </summary>
        public static string RightsAcquired {
            get {
                return ResourceManager.GetString("RightsAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights Acquired.
        /// </summary>
        public static string RightsAcquiredDisplay {
            get {
                return ResourceManager.GetString("RightsAcquiredDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights Period.
        /// </summary>
        public static string RightsPeriod {
            get {
                return ResourceManager.GetString("RightsPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights Review Status.
        /// </summary>
        public static string RightsReviewStatus {
            get {
                return ResourceManager.GetString("RightsReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Use.
        /// </summary>
        public static string Sampleuse {
            get {
                return ResourceManager.GetString("Sampleuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Contract.
        /// </summary>
        public static string SearchContractTitle {
            get {
                return ResourceManager.GetString("SearchContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Contract.
        /// </summary>
        public static string SearchForContact {
            get {
                return ResourceManager.GetString("SearchForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search using Release Parameters.
        /// </summary>
        public static string SearchusingReleaseParametersHeading {
            get {
                return ResourceManager.GetString("SearchusingReleaseParametersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide search criteria.
        /// </summary>
        public static string searchValidation {
            get {
                return ResourceManager.GetString("searchValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        public static string SecExploitation {
            get {
                return ResourceManager.GetString("SecExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitation Types.
        /// </summary>
        public static string SecondaryExploitation {
            get {
                return ResourceManager.GetString("SecondaryExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryExploitationBasicSearch.
        /// </summary>
        public static string SecondaryExploitationBasicSearch {
            get {
                return ResourceManager.GetString("SecondaryExploitationBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Digital Restrictions/.
        /// </summary>
        public static string SecondaryExploitationBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("SecondaryExploitationBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryExploitationReleaseParameters.
        /// </summary>
        public static string SecondaryExploitationReleaseParameters {
            get {
                return ResourceManager.GetString("SecondaryExploitationReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights &amp; Secondary Exploitation.
        /// </summary>
        public static string SecondaryExploitationReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("SecondaryExploitationReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SecondaryExploitation Types available!.
        /// </summary>
        public static string SecondaryExploitationTypesNotAvailable {
            get {
                return ResourceManager.GetString("SecondaryExploitationTypesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Countries from below list.
        /// </summary>
        public static string SelectCountries {
            get {
                return ResourceManager.GetString("SelectCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Countries.
        /// </summary>
        public static string SelectedCountries {
            get {
                return ResourceManager.GetString("SelectedCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Remove Countries.
        /// </summary>
        public static string SelectRemoveCountries {
            get {
                return ResourceManager.GetString("SelectRemoveCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Remove Countries.
        /// </summary>
        public static string SelectRemoveCountriesLink {
            get {
                return ResourceManager.GetString("SelectRemoveCountriesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a future Lost Rights &apos;To’ date, so please be aware that the search results will only include repertoire for which you are authorised to view &apos;sensitive data&apos;.
        /// </summary>
        public static string SenstivePrivilege {
            get {
                return ResourceManager.GetString("SenstivePrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowDropDown {
            get {
                return ResourceManager.GetString("ShowDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation.
        /// </summary>
        public static string Synchronisation {
            get {
                return ResourceManager.GetString("Synchronisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/TempFiles.
        /// </summary>
        public static string TempFilePath {
            get {
                return ResourceManager.GetString("TempFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territorial Rights.
        /// </summary>
        public static string TerritorialRights {
            get {
                return ResourceManager.GetString("TerritorialRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territorial Rights.
        /// </summary>
        public static string TerritorialRightsDisplay {
            get {
                return ResourceManager.GetString("TerritorialRightsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitation Countries.
        /// </summary>
        public static string TerritorialRightsLabel {
            get {
                return ResourceManager.GetString("TerritorialRightsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Price Compilation.
        /// </summary>
        public static string TopPriceCompilation {
            get {
                return ResourceManager.GetString("TopPriceCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TracksBasicSearch.
        /// </summary>
        public static string TracksBasicSearch {
            get {
                return ResourceManager.GetString("TracksBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights/Show Tracks/.
        /// </summary>
        public static string TracksBasicSearchPageHeading {
            get {
                return ResourceManager.GetString("TracksBasicSearchPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track&apos;s Rights Parameter.
        /// </summary>
        public static string TracksRightsParameter {
            get {
                return ResourceManager.GetString("TracksRightsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TracksSearchReleaseParameters.
        /// </summary>
        public static string TracksSearchReleaseParameters {
            get {
                return ResourceManager.GetString("TracksSearchReleaseParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertoire Rights Search/Rights/Show Tracks/.
        /// </summary>
        public static string TracksSearchReleaseParametersPageHeading {
            get {
                return ResourceManager.GetString("TracksSearchReleaseParametersPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC.
        /// </summary>
        public static string UPC {
            get {
                return ResourceManager.GetString("UPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file uploaded contains more than 500 records, please upload a file containing less than or equal to 500 records..
        /// </summary>
        public static string UploadedFileRecordsExceed {
            get {
                return ResourceManager.GetString("UploadedFileRecordsExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Type.
        /// </summary>
        public static string UseType {
            get {
                return ResourceManager.GetString("UseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Title.
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
