//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMGI.GRCS.Resx.Resource.UIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoutingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoutingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMGI.GRCS.Resx.Resource.UIResources.RoutingResource", typeof(RoutingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Rules.
        /// </summary>
        public static string Js_ExistingRules {
            get {
                return ResourceManager.GetString("Js_ExistingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Routing Variations.
        /// </summary>
        public static string Js_PgTitle_ManageRoutingVariations {
            get {
                return ResourceManager.GetString("Js_PgTitle_ManageRoutingVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Variation.
        /// </summary>
        public static string JsBtn_AddVariation {
            get {
                return ResourceManager.GetString("JsBtn_AddVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string JsBtn_ExporttoExcel {
            get {
                return ResourceManager.GetString("JsBtn_ExporttoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule.
        /// </summary>
        public static string JsBtn_NewRule {
            get {
                return ResourceManager.GetString("JsBtn_NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string JsBtn_SaveAs {
            get {
                return ResourceManager.GetString("JsBtn_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string JsCntrlBtnName_Add {
            get {
                return ResourceManager.GetString("JsCntrlBtnName_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string JsCntrlName_Activate {
            get {
                return ResourceManager.GetString("JsCntrlName_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string JsCntrlName_deactivate {
            get {
                return ResourceManager.GetString("JsCntrlName_deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string JsCntrlName_Master {
            get {
                return ResourceManager.GetString("JsCntrlName_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string JsCntrlName_No {
            get {
                return ResourceManager.GetString("JsCntrlName_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular / Non Traditional.
        /// </summary>
        public static string JsCntrlName_Regular {
            get {
                return ResourceManager.GetString("JsCntrlName_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Manage.
        /// </summary>
        public static string JsCntrlName_ViewOrManage {
            get {
                return ResourceManager.GetString("JsCntrlName_ViewOrManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string JsCntrlName_Yes {
            get {
                return ResourceManager.GetString("JsCntrlName_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Artist.
        /// </summary>
        public static string jsJtabl_ActiveArtist {
            get {
                return ResourceManager.GetString("jsJtabl_ActiveArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string JsJtabl_AdditionalInfo {
            get {
                return ResourceManager.GetString("JsJtabl_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string jsJtabl_Comments {
            get {
                return ResourceManager.GetString("jsJtabl_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation.
        /// </summary>
        public static string jsJtabl_Compilation {
            get {
                return ResourceManager.GetString("jsJtabl_Compilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Artist.
        /// </summary>
        public static string jsJtabl_MultiArtist {
            get {
                return ResourceManager.GetString("jsJtabl_MultiArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owning Company.
        /// </summary>
        public static string jsJtabl_OwningCompany {
            get {
                return ResourceManager.GetString("jsJtabl_OwningCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owning Territory.
        /// </summary>
        public static string jsJtabl_OwningTerritory {
            get {
                return ResourceManager.GetString("jsJtabl_OwningTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string jsJtabl_ProjectType {
            get {
                return ResourceManager.GetString("jsJtabl_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Territory.
        /// </summary>
        public static string jsJtabl_ReleaseTerritory {
            get {
                return ResourceManager.GetString("jsJtabl_ReleaseTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Company.
        /// </summary>
        public static string jsJtabl_RequestingCompany {
            get {
                return ResourceManager.GetString("jsJtabl_RequestingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Territory.
        /// </summary>
        public static string jsJtabl_RequestingTerritory {
            get {
                return ResourceManager.GetString("jsJtabl_RequestingTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string jsJtabl_RequestType {
            get {
                return ResourceManager.GetString("jsJtabl_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string jsJtabl_RuleName {
            get {
                return ResourceManager.GetString("jsJtabl_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Number.
        /// </summary>
        public static string jsJtabl_RuleNumber {
            get {
                return ResourceManager.GetString("jsJtabl_RuleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string JsJtabl_Select {
            get {
                return ResourceManager.GetString("JsJtabl_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitive Artist.
        /// </summary>
        public static string jsJtabl_SensitiveArtist {
            get {
                return ResourceManager.GetString("jsJtabl_SensitiveArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip International Marketing.
        /// </summary>
        public static string jsJtabl_SkipInterMarketing {
            get {
                return ResourceManager.GetString("jsJtabl_SkipInterMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Local Label Marketing.
        /// </summary>
        public static string jsJtabl_SkipLocalLabelMarketing {
            get {
                return ResourceManager.GetString("jsJtabl_SkipLocalLabelMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip National Marketing.
        /// </summary>
        public static string jsJtabl_SkipNatMarketing {
            get {
                return ResourceManager.GetString("jsJtabl_SkipNatMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent.
        /// </summary>
        public static string jsJtabl_Talent {
            get {
                return ResourceManager.GetString("jsJtabl_Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string jsJtabl_Update {
            get {
                return ResourceManager.GetString("jsJtabl_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Rule Name..
        /// </summary>
        public static string JsMsg_EnterRuleName {
            get {
                return ResourceManager.GetString("JsMsg_EnterRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the parent rule will also delete all the variations. Do you want to continue?.
        /// </summary>
        public static string JsMsg_ParentRuleDeleteConfirmation {
            get {
                return ResourceManager.GetString("JsMsg_ParentRuleDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent rule saved successfully..
        /// </summary>
        public static string JsMsg_ParentRuleSaved {
            get {
                return ResourceManager.GetString("JsMsg_ParentRuleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data....
        /// </summary>
        public static string JsMsg_RetrievingData {
            get {
                return ResourceManager.GetString("JsMsg_RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule has been activated successfully..
        /// </summary>
        public static string JsMsg_RuleActivatedSuccess {
            get {
                return ResourceManager.GetString("JsMsg_RuleActivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule has been deactivated successfully..
        /// </summary>
        public static string JsMsg_RuleDeactivatedSuccess {
            get {
                return ResourceManager.GetString("JsMsg_RuleDeactivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule has been removed successfully..
        /// </summary>
        public static string JsMsg_RuleRemovedSuccess {
            get {
                return ResourceManager.GetString("JsMsg_RuleRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select atleast one artist..
        /// </summary>
        public static string JsMsg_SelectOneArtist {
            get {
                return ResourceManager.GetString("JsMsg_SelectOneArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Rule.
        /// </summary>
        public static string JsMsg_Title_CreateRule {
            get {
                return ResourceManager.GetString("JsMsg_Title_CreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Artist.
        /// </summary>
        public static string JsMsg_Title_MngArtist {
            get {
                return ResourceManager.GetString("JsMsg_Title_MngArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Owning Company.
        /// </summary>
        public static string JsMsg_Title_MngOwnCompany {
            get {
                return ResourceManager.GetString("JsMsg_Title_MngOwnCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Owning Territory.
        /// </summary>
        public static string JsMsg_Title_MngOwnTerritory {
            get {
                return ResourceManager.GetString("JsMsg_Title_MngOwnTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Release Territory.
        /// </summary>
        public static string JsMsg_Title_MngRelTerritory {
            get {
                return ResourceManager.GetString("JsMsg_Title_MngRelTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Requesting Company.
        /// </summary>
        public static string JsMsg_Title_MngReqCompany {
            get {
                return ResourceManager.GetString("JsMsg_Title_MngReqCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Requesting Territory.
        /// </summary>
        public static string JsMsg_Title_MngReqTerritory {
            get {
                return ResourceManager.GetString("JsMsg_Title_MngReqTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation has been activated successfully..
        /// </summary>
        public static string JsMsg_VariationActivatedSuccess {
            get {
                return ResourceManager.GetString("JsMsg_VariationActivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation has been deactivated successfully..
        /// </summary>
        public static string JsMsg_VariationDeactivatedSuccess {
            get {
                return ResourceManager.GetString("JsMsg_VariationDeactivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation has been removed successfully..
        /// </summary>
        public static string JsMsg_VariationRemovedSuccess {
            get {
                return ResourceManager.GetString("JsMsg_VariationRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variations added successfully..
        /// </summary>
        public static string JsMsg_VariationsAdded {
            get {
                return ResourceManager.GetString("JsMsg_VariationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variations saved successfully..
        /// </summary>
        public static string JsMsg_VariationSaved {
            get {
                return ResourceManager.GetString("JsMsg_VariationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MangeRuleVariations.
        /// </summary>
        public static string JsPageName_MangeRuleVariations {
            get {
                return ResourceManager.GetString("JsPageName_MangeRuleVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string JsPageName_Rules {
            get {
                return ResourceManager.GetString("JsPageName_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule&amp;nbsp;.
        /// </summary>
        public static string JsTxt_Rule {
            get {
                return ResourceManager.GetString("JsTxt_Rule", resourceCulture);
            }
        }
    }
}
