//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace WSPeopleSearchServiceProxy
{
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'UsingAddressing' from namespace 'http://www.w3.org/2006/05/addressing/wsdl' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WSPeopleSearchServiceSoapBinding", Namespace = "http://search.ws.rms.umusic.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSTalent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSearchResult))]
    public partial class WSPeopleSearchServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getDuplicateListOperationCompleted;

        private System.Threading.SendOrPostCallback getBySearchOperationCompleted;

        private System.Threading.SendOrPostCallback getByIdListOperationCompleted;

        private System.Threading.SendOrPostCallback getByContextOperationCompleted;

        private System.Threading.SendOrPostCallback getByIdOperationCompleted;

        /// <remarks/>
        public WSPeopleSearchServiceService()
        {
            this.Url = "https://r2test.umusic.net:443/r2/People/services/WSPeopleSearchService";
        }

        /// <remarks/>
        public event getDuplicateListCompletedEventHandler getDuplicateListCompleted;

        /// <remarks/>
        public event getBySearchCompletedEventHandler getBySearchCompleted;

        /// <remarks/>
        public event getByIdListCompletedEventHandler getByIdListCompleted;

        /// <remarks/>
        public event getByContextCompletedEventHandler getByContextCompleted;

        /// <remarks/>
        public event getByIdCompletedEventHandler getByIdCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getDuplicateList", RequestNamespace = "http://search.ws.rms.umusic.com", ResponseNamespace = "http://search.ws.rms.umusic.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDuplicateListReturn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public WSPeopleSearchResult getDuplicateList([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSPeopleDuplicateCheck wsPeopleDuplicateCheck, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSSearchOption wsSearchOption, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] System.Nullable<AccountScope> accountScope)
        {
            object[] results = this.Invoke("getDuplicateList", new object[] {
                        wsPeopleDuplicateCheck,
                        wsSearchOption,
                        accountScope});
            return ((WSPeopleSearchResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetDuplicateList(WSPeopleDuplicateCheck wsPeopleDuplicateCheck, WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getDuplicateList", new object[] {
                        wsPeopleDuplicateCheck,
                        wsSearchOption,
                        accountScope}, callback, asyncState);
        }

        /// <remarks/>
        public WSPeopleSearchResult EndgetDuplicateList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSPeopleSearchResult)(results[0]));
        }

        /// <remarks/>
        public void getDuplicateListAsync(WSPeopleDuplicateCheck wsPeopleDuplicateCheck, WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope)
        {
            this.getDuplicateListAsync(wsPeopleDuplicateCheck, wsSearchOption, accountScope, null);
        }

        /// <remarks/>
        public void getDuplicateListAsync(WSPeopleDuplicateCheck wsPeopleDuplicateCheck, WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope, object userState)
        {
            if ((this.getDuplicateListOperationCompleted == null))
            {
                this.getDuplicateListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDuplicateListOperationCompleted);
            }
            this.InvokeAsync("getDuplicateList", new object[] {
                        wsPeopleDuplicateCheck,
                        wsSearchOption,
                        accountScope}, this.getDuplicateListOperationCompleted, userState);
        }

        private void OngetDuplicateListOperationCompleted(object arg)
        {
            if ((this.getDuplicateListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDuplicateListCompleted(this, new getDuplicateListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getBySearch", RequestNamespace = "http://search.ws.rms.umusic.com", ResponseNamespace = "http://search.ws.rms.umusic.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getBySearchReturn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public WSPeopleSearchResult getBySearch([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSPeopleSearch wsPeopleSearch, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSSearchOption wsSearchOption, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] System.Nullable<AccountScope> accountScope)
        {
            object[] results = this.Invoke("getBySearch", new object[] {
                        wsPeopleSearch,
                        wsSearchOption,
                        accountScope});
            return ((WSPeopleSearchResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetBySearch(WSPeopleSearch wsPeopleSearch, WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getBySearch", new object[] {
                        wsPeopleSearch,
                        wsSearchOption,
                        accountScope}, callback, asyncState);
        }

        /// <remarks/>
        public WSPeopleSearchResult EndgetBySearch(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSPeopleSearchResult)(results[0]));
        }

        /// <remarks/>
        public void getBySearchAsync(WSPeopleSearch wsPeopleSearch, WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope)
        {
            this.getBySearchAsync(wsPeopleSearch, wsSearchOption, accountScope, null);
        }

        /// <remarks/>
        public void getBySearchAsync(WSPeopleSearch wsPeopleSearch, WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope, object userState)
        {
            if ((this.getBySearchOperationCompleted == null))
            {
                this.getBySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBySearchOperationCompleted);
            }
            this.InvokeAsync("getBySearch", new object[] {
                        wsPeopleSearch,
                        wsSearchOption,
                        accountScope}, this.getBySearchOperationCompleted, userState);
        }

        private void OngetBySearchOperationCompleted(object arg)
        {
            if ((this.getBySearchCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBySearchCompleted(this, new getBySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getByIdList", RequestNamespace = "http://search.ws.rms.umusic.com", ResponseNamespace = "http://search.ws.rms.umusic.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getByIdListReturn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSPeople[] getByIdList([System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] talentNameIdArray, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSSearchOption wsSearchOption)
        {
            object[] results = this.Invoke("getByIdList", new object[] {
                        talentNameIdArray,
                        wsSearchOption});
            return ((WSPeople[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetByIdList(string[] talentNameIdArray, WSSearchOption wsSearchOption, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getByIdList", new object[] {
                        talentNameIdArray,
                        wsSearchOption}, callback, asyncState);
        }

        /// <remarks/>
        public WSPeople[] EndgetByIdList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSPeople[])(results[0]));
        }

        /// <remarks/>
        public void getByIdListAsync(string[] talentNameIdArray, WSSearchOption wsSearchOption)
        {
            this.getByIdListAsync(talentNameIdArray, wsSearchOption, null);
        }

        /// <remarks/>
        public void getByIdListAsync(string[] talentNameIdArray, WSSearchOption wsSearchOption, object userState)
        {
            if ((this.getByIdListOperationCompleted == null))
            {
                this.getByIdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByIdListOperationCompleted);
            }
            this.InvokeAsync("getByIdList", new object[] {
                        talentNameIdArray,
                        wsSearchOption}, this.getByIdListOperationCompleted, userState);
        }

        private void OngetByIdListOperationCompleted(object arg)
        {
            if ((this.getByIdListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByIdListCompleted(this, new getByIdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getByContext", RequestNamespace = "http://search.ws.rms.umusic.com", ResponseNamespace = "http://search.ws.rms.umusic.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getByContextReturn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public WSPeopleSearchResult getByContext([System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] uniqueIdList, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] System.Nullable<RepertoireType> contextRepertoireType, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string primaryIndicator, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSSearchOption wsSearchOption)
        {
            object[] results = this.Invoke("getByContext", new object[] {
                        uniqueIdList,
                        contextRepertoireType,
                        primaryIndicator,
                        wsSearchOption});
            return ((WSPeopleSearchResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetByContext(string[] uniqueIdList, System.Nullable<RepertoireType> contextRepertoireType, string primaryIndicator, WSSearchOption wsSearchOption, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getByContext", new object[] {
                        uniqueIdList,
                        contextRepertoireType,
                        primaryIndicator,
                        wsSearchOption}, callback, asyncState);
        }

        /// <remarks/>
        public WSPeopleSearchResult EndgetByContext(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSPeopleSearchResult)(results[0]));
        }

        /// <remarks/>
        public void getByContextAsync(string[] uniqueIdList, System.Nullable<RepertoireType> contextRepertoireType, string primaryIndicator, WSSearchOption wsSearchOption)
        {
            this.getByContextAsync(uniqueIdList, contextRepertoireType, primaryIndicator, wsSearchOption, null);
        }

        /// <remarks/>
        public void getByContextAsync(string[] uniqueIdList, System.Nullable<RepertoireType> contextRepertoireType, string primaryIndicator, WSSearchOption wsSearchOption, object userState)
        {
            if ((this.getByContextOperationCompleted == null))
            {
                this.getByContextOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByContextOperationCompleted);
            }
            this.InvokeAsync("getByContext", new object[] {
                        uniqueIdList,
                        contextRepertoireType,
                        primaryIndicator,
                        wsSearchOption}, this.getByContextOperationCompleted, userState);
        }

        private void OngetByContextOperationCompleted(object arg)
        {
            if ((this.getByContextCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByContextCompleted(this, new getByContextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getById", RequestNamespace = "http://search.ws.rms.umusic.com", ResponseNamespace = "http://search.ws.rms.umusic.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getByIdReturn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public WSPeople getById([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string talentNameId, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] WSSearchOption wsSearchOption)
        {
            object[] results = this.Invoke("getById", new object[] {
                        talentNameId,
                        wsSearchOption});
            return ((WSPeople)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetById(string talentNameId, WSSearchOption wsSearchOption, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getById", new object[] {
                        talentNameId,
                        wsSearchOption}, callback, asyncState);
        }

        /// <remarks/>
        public WSPeople EndgetById(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSPeople)(results[0]));
        }

        /// <remarks/>
        public void getByIdAsync(string talentNameId, WSSearchOption wsSearchOption)
        {
            this.getByIdAsync(talentNameId, wsSearchOption, null);
        }

        /// <remarks/>
        public void getByIdAsync(string talentNameId, WSSearchOption wsSearchOption, object userState)
        {
            if ((this.getByIdOperationCompleted == null))
            {
                this.getByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByIdOperationCompleted);
            }
            this.InvokeAsync("getById", new object[] {
                        talentNameId,
                        wsSearchOption}, this.getByIdOperationCompleted, userState);
        }

        private void OngetByIdOperationCompleted(object arg)
        {
            if ((this.getByIdCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByIdCompleted(this, new getByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://search.ws.rms.umusic.com")]
    public partial class WSPeopleDuplicateCheck
    {

        private string firstNameField;

        private string lastNameField;

        private string talentNameIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string talentNameId
        {
            get
            {
                return this.talentNameIdField;
            }
            set
            {
                this.talentNameIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://search.ws.rms.umusic.com")]
    public partial class WSPeopleSearch
    {

        private string contributionPrimaryIndicatorField;

        private System.Nullable<DQStatus> dqStatusField;

        private string externalKeyTypeField;

        private string externalKeyValueField;

        private System.Nullable<SearchOption> externalKeyOptionField;

        private string firstNameField;

        private System.Nullable<SearchOption> firstNameOptionField;

        private string fullNameField;

        private string lastNameField;

        private System.Nullable<SearchOption> lastNameOptionField;

        private System.Nullable<bool> multiFieldFlagField;

        private System.Nullable<RoleGroup> roleGroupField;

        private string roleNoField;

        private string talentNameIdField;

        private string titleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string contributionPrimaryIndicator
        {
            get
            {
                return this.contributionPrimaryIndicatorField;
            }
            set
            {
                this.contributionPrimaryIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<DQStatus> dqStatus
        {
            get
            {
                return this.dqStatusField;
            }
            set
            {
                this.dqStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string externalKeyType
        {
            get
            {
                return this.externalKeyTypeField;
            }
            set
            {
                this.externalKeyTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string externalKeyValue
        {
            get
            {
                return this.externalKeyValueField;
            }
            set
            {
                this.externalKeyValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<SearchOption> externalKeyOption
        {
            get
            {
                return this.externalKeyOptionField;
            }
            set
            {
                this.externalKeyOptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<SearchOption> firstNameOption
        {
            get
            {
                return this.firstNameOptionField;
            }
            set
            {
                this.firstNameOptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<SearchOption> lastNameOption
        {
            get
            {
                return this.lastNameOptionField;
            }
            set
            {
                this.lastNameOptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<bool> multiFieldFlag
        {
            get
            {
                return this.multiFieldFlagField;
            }
            set
            {
                this.multiFieldFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<RoleGroup> roleGroup
        {
            get
            {
                return this.roleGroupField;
            }
            set
            {
                this.roleGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string roleNo
        {
            get
            {
                return this.roleNoField;
            }
            set
            {
                this.roleNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string talentNameId
        {
            get
            {
                return this.talentNameIdField;
            }
            set
            {
                this.talentNameIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public enum DQStatus
    {

        /// <remarks/>
        ALL_,

        /// <remarks/>
        DQAPRV,

        /// <remarks/>
        DIRTYX,

        /// <remarks/>
        NEWXXX,

        /// <remarks/>
        CERT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public enum SearchOption
    {

        /// <remarks/>
        CONTAINS,

        /// <remarks/>
        EXACT_MATCH,

        /// <remarks/>
        STARTS_WITH,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public enum RoleGroup
    {

        /// <remarks/>
        ALL_,

        /// <remarks/>
        ACTOR_,

        /// <remarks/>
        DIRECT_,

        /// <remarks/>
        ARRANG,

        /// <remarks/>
        ARTIST,

        /// <remarks/>
        ARTWRK,

        /// <remarks/>
        MUSSYN,

        /// <remarks/>
        MUSENS,

        /// <remarks/>
        WRITER,

        /// <remarks/>
        VIDPRO,

        /// <remarks/>
        PRODCR,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        MUSWOO,

        /// <remarks/>
        MUSVOC,

        /// <remarks/>
        MUSSTR,

        /// <remarks/>
        MUSPER,

        /// <remarks/>
        OTHER2,

        /// <remarks/>
        WRITR2,

        /// <remarks/>
        GRAPHA,

        /// <remarks/>
        PHOTOG,

        /// <remarks/>
        MUSOTH,

        /// <remarks/>
        MUSKEY,

        /// <remarks/>
        ENGIN,

        /// <remarks/>
        MIXER,

        /// <remarks/>
        MSTENG,

        /// <remarks/>
        MUSBRS,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSPeople))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://search.ws.rms.umusic.com")]
    public partial class WSTalent
    {

        private string companyDisplayField;

        private string companyIdField;

        private string countryDisplayField;

        private string countryIdField;

        private string dqStatusField;

        private string dqStatusDisplayField;

        private string originField;

        private string originDisplayField;

        private string searchInformationField;

        private string talentIdField;

        private string talentTypeField;

        private string talentNameIdField;

        private string translationIndicatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string companyDisplay
        {
            get
            {
                return this.companyDisplayField;
            }
            set
            {
                this.companyDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string countryDisplay
        {
            get
            {
                return this.countryDisplayField;
            }
            set
            {
                this.countryDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string dqStatus
        {
            get
            {
                return this.dqStatusField;
            }
            set
            {
                this.dqStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string dqStatusDisplay
        {
            get
            {
                return this.dqStatusDisplayField;
            }
            set
            {
                this.dqStatusDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string originDisplay
        {
            get
            {
                return this.originDisplayField;
            }
            set
            {
                this.originDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string searchInformation
        {
            get
            {
                return this.searchInformationField;
            }
            set
            {
                this.searchInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string talentId
        {
            get
            {
                return this.talentIdField;
            }
            set
            {
                this.talentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string talentType
        {
            get
            {
                return this.talentTypeField;
            }
            set
            {
                this.talentTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string talentNameId
        {
            get
            {
                return this.talentNameIdField;
            }
            set
            {
                this.talentNameIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string translationIndicator
        {
            get
            {
                return this.translationIndicatorField;
            }
            set
            {
                this.translationIndicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://search.ws.rms.umusic.com")]
    public partial class WSPeople : WSTalent
    {

        private string abbreviatedNameField;

        private string acquisitionSourceField;

        private string acquisitionSourceDisplayField;

        private string catalogIndicatorField;

        private string dateOfBirthYearField;

        private string dateOfDeathYearField;

        private string displayNameField;

        private string firstNameField;

        private string formattedNameField;

        private string lastNameField;

        private string lastNamePrefixField;

        private string rolesPerformedListField;

        private string titleField;

        private string accountIdField;

        private string accountNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string abbreviatedName
        {
            get
            {
                return this.abbreviatedNameField;
            }
            set
            {
                this.abbreviatedNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string acquisitionSource
        {
            get
            {
                return this.acquisitionSourceField;
            }
            set
            {
                this.acquisitionSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string acquisitionSourceDisplay
        {
            get
            {
                return this.acquisitionSourceDisplayField;
            }
            set
            {
                this.acquisitionSourceDisplayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string catalogIndicator
        {
            get
            {
                return this.catalogIndicatorField;
            }
            set
            {
                this.catalogIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string dateOfBirthYear
        {
            get
            {
                return this.dateOfBirthYearField;
            }
            set
            {
                this.dateOfBirthYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string dateOfDeathYear
        {
            get
            {
                return this.dateOfDeathYearField;
            }
            set
            {
                this.dateOfDeathYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string formattedName
        {
            get
            {
                return this.formattedNameField;
            }
            set
            {
                this.formattedNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string lastNamePrefix
        {
            get
            {
                return this.lastNamePrefixField;
            }
            set
            {
                this.lastNamePrefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string rolesPerformedList
        {
            get
            {
                return this.rolesPerformedListField;
            }
            set
            {
                this.rolesPerformedListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string accountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSPeopleSearchResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public partial class WSSearchResult
    {

        private long durationField;

        private int searchTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int searchType
        {
            get
            {
                return this.searchTypeField;
            }
            set
            {
                this.searchTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://search.ws.rms.umusic.com")]
    public partial class WSPeopleSearchResult : WSSearchResult
    {

        private WSPeople[] resultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSPeople[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public partial class WSSearchOption
    {

        private string companyIdField;

        private string countryIdField;

        private string maxResultRowsField;

        private bool verboseField;

        private string directionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string maxResultRows
        {
            get
            {
                return this.maxResultRowsField;
            }
            set
            {
                this.maxResultRowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool verbose
        {
            get
            {
                return this.verboseField;
            }
            set
            {
                this.verboseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public enum AccountScope
    {

        /// <remarks/>
        ALL,

        /// <remarks/>
        OWNED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.ws.rms.umusic.com")]
    public enum RepertoireType
    {

        /// <remarks/>
        RESOURCE,

        /// <remarks/>
        RELEASE,

        /// <remarks/>
        PROJECT,

        /// <remarks/>
        PEOPLE,

        /// <remarks/>
        WORK,

        /// <remarks/>
        COMPANY,

        /// <remarks/>
        RESOURCE_GROUP,

        /// <remarks/>
        SERIES,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getDuplicateListCompletedEventHandler(object sender, getDuplicateListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDuplicateListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getDuplicateListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSPeopleSearchResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSPeopleSearchResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getBySearchCompletedEventHandler(object sender, getBySearchCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getBySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSPeopleSearchResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSPeopleSearchResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getByIdListCompletedEventHandler(object sender, getByIdListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByIdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getByIdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSPeople[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSPeople[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getByContextCompletedEventHandler(object sender, getByContextCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByContextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getByContextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSPeopleSearchResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSPeopleSearchResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getByIdCompletedEventHandler(object sender, getByIdCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSPeople Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSPeople)(this.results[0]));
            }
        }
    }
}
