//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSResourceGroupSearchServiceProxy
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    public partial class WSRMSException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("WSRMSException", "http://common.ws.rms.umusic.com");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://search.ws.rms.umusic.com", ConfigurationName="WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService")]
    public interface WSResourceGroupSearchService
    {
        
        // CODEGEN: Parameter 'getByIdReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSResourceGroupSearchServiceProxy.WSRMSException), Action="getById", Name="WSRMSException", Namespace="http://common.ws.rms.umusic.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSSearchResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getByIdReturn")]
        WSResourceGroupSearchServiceProxy.getByIdResponse getById(WSResourceGroupSearchServiceProxy.getByIdRequest request);
        
        // CODEGEN: Parameter 'getContributionsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getContributions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSResourceGroupSearchServiceProxy.WSRMSException), Action="getContributions", Name="WSRMSException", Namespace="http://common.ws.rms.umusic.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSSearchResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getContributionsReturn")]
        WSResourceGroupSearchServiceProxy.getContributionsResponse getContributions(WSResourceGroupSearchServiceProxy.getContributionsRequest request);
        
        // CODEGEN: Parameter 'getBySearchReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getBySearch", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSResourceGroupSearchServiceProxy.WSRMSException), Action="getBySearch", Name="WSRMSException", Namespace="http://common.ws.rms.umusic.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSSearchResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBySearchReturn")]
        WSResourceGroupSearchServiceProxy.getBySearchResponse getBySearch(WSResourceGroupSearchServiceProxy.getBySearchRequest request);
        
        // CODEGEN: Parameter 'getByIdListReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getByIdList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSResourceGroupSearchServiceProxy.WSRMSException), Action="getByIdList", Name="WSRMSException", Namespace="http://common.ws.rms.umusic.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSSearchResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getByIdListReturn")]
        WSResourceGroupSearchServiceProxy.getByIdListResponse getByIdList(WSResourceGroupSearchServiceProxy.getByIdListRequest request);
        
        // CODEGEN: Parameter 'getByContextReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getByContext", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSResourceGroupSearchServiceProxy.WSRMSException), Action="getByContext", Name="WSRMSException", Namespace="http://common.ws.rms.umusic.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSSearchResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getByContextReturn")]
        WSResourceGroupSearchServiceProxy.getByContextResponse getByContext(WSResourceGroupSearchServiceProxy.getByContextRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public partial class WSSearchOption
    {
        
        private string companyIdField;
        
        private string countryIdField;
        
        private string maxResultRowsField;
        
        private bool verboseField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string maxResultRows
        {
            get
            {
                return this.maxResultRowsField;
            }
            set
            {
                this.maxResultRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool verbose
        {
            get
            {
                return this.verboseField;
            }
            set
            {
                this.verboseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSResourceGroupSearchResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public partial class WSSearchResult
    {
        
        private long durationField;
        
        private int searchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int searchType
        {
            get
            {
                return this.searchTypeField;
            }
            set
            {
                this.searchTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.ws.rms.umusic.com")]
    public partial class WSResourceGroupSearchResult : WSSearchResult
    {
        
        private WSResourceGroup[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSResourceGroup[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.ws.rms.umusic.com")]
    public partial class WSResourceGroup
    {
        
        private string companyDisplayField;
        
        private string companyIdField;
        
        private string formattedTitleField;
        
        private string groupIdField;
        
        private string groupTypeField;
        
        private string groupTypeDisplayField;
        
        private string musicTypeField;
        
        private string musicTypeDisplayField;
        
        private string pcNoticeCompanyDisplayField;
        
        private string pcNoticeCompanyIdField;
        
        private string pcNoticeYearField;
        
        private string resourceGroupIdField;
        
        private string statusField;
        
        private string statusDisplayField;
        
        private string titleField;
        
        private string versionTitleField;
        
        private string workContributorListField;
        
        private string workTitleField;
        
        private string workIdField;
        
        private string resourceContributorListField;
        
        private string pcNoticeExtensionField;
        
        private string accountIdField;
        
        private string accountNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string companyDisplay
        {
            get
            {
                return this.companyDisplayField;
            }
            set
            {
                this.companyDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string formattedTitle
        {
            get
            {
                return this.formattedTitleField;
            }
            set
            {
                this.formattedTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string groupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string groupType
        {
            get
            {
                return this.groupTypeField;
            }
            set
            {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string groupTypeDisplay
        {
            get
            {
                return this.groupTypeDisplayField;
            }
            set
            {
                this.groupTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string musicType
        {
            get
            {
                return this.musicTypeField;
            }
            set
            {
                this.musicTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string musicTypeDisplay
        {
            get
            {
                return this.musicTypeDisplayField;
            }
            set
            {
                this.musicTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string pcNoticeCompanyDisplay
        {
            get
            {
                return this.pcNoticeCompanyDisplayField;
            }
            set
            {
                this.pcNoticeCompanyDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string pcNoticeCompanyId
        {
            get
            {
                return this.pcNoticeCompanyIdField;
            }
            set
            {
                this.pcNoticeCompanyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string pcNoticeYear
        {
            get
            {
                return this.pcNoticeYearField;
            }
            set
            {
                this.pcNoticeYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string resourceGroupId
        {
            get
            {
                return this.resourceGroupIdField;
            }
            set
            {
                this.resourceGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string statusDisplay
        {
            get
            {
                return this.statusDisplayField;
            }
            set
            {
                this.statusDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string versionTitle
        {
            get
            {
                return this.versionTitleField;
            }
            set
            {
                this.versionTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string workContributorList
        {
            get
            {
                return this.workContributorListField;
            }
            set
            {
                this.workContributorListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string workTitle
        {
            get
            {
                return this.workTitleField;
            }
            set
            {
                this.workTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string workId
        {
            get
            {
                return this.workIdField;
            }
            set
            {
                this.workIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string resourceContributorList
        {
            get
            {
                return this.resourceContributorListField;
            }
            set
            {
                this.resourceContributorListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string pcNoticeExtension
        {
            get
            {
                return this.pcNoticeExtensionField;
            }
            set
            {
                this.pcNoticeExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string accountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.ws.rms.umusic.com")]
    public partial class WSResourceGroupSearch
    {
        
        private bool aliasesIndicator1Field;
        
        private bool aliasesIndicator2Field;
        
        private bool aliasesIndicator3Field;
        
        private string companyIdField;
        
        private string groupIdField;
        
        private System.Nullable<ResourceGroupType> groupTypeField;
        
        private bool multiFieldFlagField;
        
        private System.Nullable<MusicType> musicTypeField;
        
        private string pcNoticeCompanyIdField;
        
        private string pcNoticeYearField;
        
        private System.Nullable<RoleGroup> roleGroup1Field;
        
        private System.Nullable<RoleGroup> roleGroup2Field;
        
        private System.Nullable<RoleGroup> roleGroup3Field;
        
        private string roleNo1Field;
        
        private string roleNo2Field;
        
        private string roleNo3Field;
        
        private System.Nullable<ResourceGroupStatus> statusField;
        
        private string talentNameId1Field;
        
        private string talentNameId2Field;
        
        private string talentNameId3Field;
        
        private System.Nullable<Operator> talentOperatorField;
        
        private string titleField;
        
        private System.Nullable<SearchOption> titleOptionField;
        
        private string versionTitleField;
        
        private System.Nullable<SearchOption> versionTitleOptionField;
        
        private string workTitleField;
        
        private System.Nullable<SearchOption> workTitleOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool aliasesIndicator1
        {
            get
            {
                return this.aliasesIndicator1Field;
            }
            set
            {
                this.aliasesIndicator1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool aliasesIndicator2
        {
            get
            {
                return this.aliasesIndicator2Field;
            }
            set
            {
                this.aliasesIndicator2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool aliasesIndicator3
        {
            get
            {
                return this.aliasesIndicator3Field;
            }
            set
            {
                this.aliasesIndicator3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string groupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<ResourceGroupType> groupType
        {
            get
            {
                return this.groupTypeField;
            }
            set
            {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool multiFieldFlag
        {
            get
            {
                return this.multiFieldFlagField;
            }
            set
            {
                this.multiFieldFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<MusicType> musicType
        {
            get
            {
                return this.musicTypeField;
            }
            set
            {
                this.musicTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string pcNoticeCompanyId
        {
            get
            {
                return this.pcNoticeCompanyIdField;
            }
            set
            {
                this.pcNoticeCompanyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string pcNoticeYear
        {
            get
            {
                return this.pcNoticeYearField;
            }
            set
            {
                this.pcNoticeYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<RoleGroup> roleGroup1
        {
            get
            {
                return this.roleGroup1Field;
            }
            set
            {
                this.roleGroup1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<RoleGroup> roleGroup2
        {
            get
            {
                return this.roleGroup2Field;
            }
            set
            {
                this.roleGroup2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<RoleGroup> roleGroup3
        {
            get
            {
                return this.roleGroup3Field;
            }
            set
            {
                this.roleGroup3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string roleNo1
        {
            get
            {
                return this.roleNo1Field;
            }
            set
            {
                this.roleNo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string roleNo2
        {
            get
            {
                return this.roleNo2Field;
            }
            set
            {
                this.roleNo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string roleNo3
        {
            get
            {
                return this.roleNo3Field;
            }
            set
            {
                this.roleNo3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public System.Nullable<ResourceGroupStatus> status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string talentNameId1
        {
            get
            {
                return this.talentNameId1Field;
            }
            set
            {
                this.talentNameId1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string talentNameId2
        {
            get
            {
                return this.talentNameId2Field;
            }
            set
            {
                this.talentNameId2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string talentNameId3
        {
            get
            {
                return this.talentNameId3Field;
            }
            set
            {
                this.talentNameId3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public System.Nullable<Operator> talentOperator
        {
            get
            {
                return this.talentOperatorField;
            }
            set
            {
                this.talentOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public System.Nullable<SearchOption> titleOption
        {
            get
            {
                return this.titleOptionField;
            }
            set
            {
                this.titleOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string versionTitle
        {
            get
            {
                return this.versionTitleField;
            }
            set
            {
                this.versionTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public System.Nullable<SearchOption> versionTitleOption
        {
            get
            {
                return this.versionTitleOptionField;
            }
            set
            {
                this.versionTitleOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public string workTitle
        {
            get
            {
                return this.workTitleField;
            }
            set
            {
                this.workTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public System.Nullable<SearchOption> workTitleOption
        {
            get
            {
                return this.workTitleOptionField;
            }
            set
            {
                this.workTitleOptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum ResourceGroupType
    {
        
        /// <remarks/>
        ALL_,
        
        /// <remarks/>
        AUDIO,
        
        /// <remarks/>
        VIDEO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum MusicType
    {
        
        /// <remarks/>
        ALL_,
        
        /// <remarks/>
        CLASSICAL,
        
        /// <remarks/>
        POP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum RoleGroup
    {
        
        /// <remarks/>
        ALL_,
        
        /// <remarks/>
        ACTOR_,
        
        /// <remarks/>
        DIRECT_,
        
        /// <remarks/>
        ARRANG,
        
        /// <remarks/>
        ARTIST,
        
        /// <remarks/>
        ARTWRK,
        
        /// <remarks/>
        MUSSYN,
        
        /// <remarks/>
        MUSENS,
        
        /// <remarks/>
        WRITER,
        
        /// <remarks/>
        VIDPRO,
        
        /// <remarks/>
        PRODCR,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        MUSWOO,
        
        /// <remarks/>
        MUSVOC,
        
        /// <remarks/>
        MUSSTR,
        
        /// <remarks/>
        MUSPER,
        
        /// <remarks/>
        OTHER2,
        
        /// <remarks/>
        WRITR2,
        
        /// <remarks/>
        GRAPHA,
        
        /// <remarks/>
        PHOTOG,
        
        /// <remarks/>
        MUSOTH,
        
        /// <remarks/>
        MUSKEY,
        
        /// <remarks/>
        ENGIN,
        
        /// <remarks/>
        MIXER,
        
        /// <remarks/>
        MSTENG,
        
        /// <remarks/>
        MUSBRS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum ResourceGroupStatus
    {
        
        /// <remarks/>
        ALL_,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum Operator
    {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum SearchOption
    {
        
        /// <remarks/>
        CONTAINS,
        
        /// <remarks/>
        EXACT_MATCH,
        
        /// <remarks/>
        STARTS_WITH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public partial class WSContribution
    {
        
        private string contributionIdField;
        
        private string labelCopyCreditField;
        
        private string primaryIndicatorField;
        
        private string musicianContractCategoryField;
        
        private string musicianContractCategoryDisplayField;
        
        private string noteField;
        
        private string repertoireTypeField;
        
        private string roleDisplayField;
        
        private string roleGroupField;
        
        private string roleGroupDisplayField;
        
        private string roleNoField;
        
        private string sequenceNoField;
        
        private string sessionIdField;
        
        private string talentNameField;
        
        private string talentNameIdField;
        
        private string uniqueIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string contributionId
        {
            get
            {
                return this.contributionIdField;
            }
            set
            {
                this.contributionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string labelCopyCredit
        {
            get
            {
                return this.labelCopyCreditField;
            }
            set
            {
                this.labelCopyCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string primaryIndicator
        {
            get
            {
                return this.primaryIndicatorField;
            }
            set
            {
                this.primaryIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string musicianContractCategory
        {
            get
            {
                return this.musicianContractCategoryField;
            }
            set
            {
                this.musicianContractCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string musicianContractCategoryDisplay
        {
            get
            {
                return this.musicianContractCategoryDisplayField;
            }
            set
            {
                this.musicianContractCategoryDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string repertoireType
        {
            get
            {
                return this.repertoireTypeField;
            }
            set
            {
                this.repertoireTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string roleDisplay
        {
            get
            {
                return this.roleDisplayField;
            }
            set
            {
                this.roleDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string roleGroup
        {
            get
            {
                return this.roleGroupField;
            }
            set
            {
                this.roleGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string roleGroupDisplay
        {
            get
            {
                return this.roleGroupDisplayField;
            }
            set
            {
                this.roleGroupDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string roleNo
        {
            get
            {
                return this.roleNoField;
            }
            set
            {
                this.roleNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string sequenceNo
        {
            get
            {
                return this.sequenceNoField;
            }
            set
            {
                this.sequenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string talentName
        {
            get
            {
                return this.talentNameField;
            }
            set
            {
                this.talentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string talentNameId
        {
            get
            {
                return this.talentNameIdField;
            }
            set
            {
                this.talentNameIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string uniqueId
        {
            get
            {
                return this.uniqueIdField;
            }
            set
            {
                this.uniqueIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.ws.rms.umusic.com")]
    public partial class WSResourceGroupContributionResult
    {
        
        private WSContribution[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSContribution[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.ws.rms.umusic.com")]
    public partial class WSResourceGroupContributionSearch
    {
        
        private string companyIdField;
        
        private string primaryIndicatorField;
        
        private string resourceGroupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string primaryIndicator
        {
            get
            {
                return this.primaryIndicatorField;
            }
            set
            {
                this.primaryIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string resourceGroupId
        {
            get
            {
                return this.resourceGroupIdField;
            }
            set
            {
                this.resourceGroupIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string resourceGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption;
        
        public getByIdRequest()
        {
        }
        
        public getByIdRequest(string resourceGroupId, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption)
        {
            this.resourceGroupId = resourceGroupId;
            this.wsSearchOption = wsSearchOption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSResourceGroup getByIdReturn;
        
        public getByIdResponse()
        {
        }
        
        public getByIdResponse(WSResourceGroupSearchServiceProxy.WSResourceGroup getByIdReturn)
        {
            this.getByIdReturn = getByIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContributions", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getContributionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSResourceGroupContributionSearch wsResourceGroupContributionSearch;
        
        public getContributionsRequest()
        {
        }
        
        public getContributionsRequest(WSResourceGroupSearchServiceProxy.WSResourceGroupContributionSearch wsResourceGroupContributionSearch)
        {
            this.wsResourceGroupContributionSearch = wsResourceGroupContributionSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContributionsResponse", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getContributionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSResourceGroupContributionResult getContributionsReturn;
        
        public getContributionsResponse()
        {
        }
        
        public getContributionsResponse(WSResourceGroupSearchServiceProxy.WSResourceGroupContributionResult getContributionsReturn)
        {
            this.getContributionsReturn = getContributionsReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum AccountScope
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        OWNED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBySearch", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getBySearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSResourceGroupSearch wsResourceGroupSearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<AccountScope> accountScope;
        
        public getBySearchRequest()
        {
        }
        
        public getBySearchRequest(WSResourceGroupSearchServiceProxy.WSResourceGroupSearch wsResourceGroupSearch, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope)
        {
            this.wsResourceGroupSearch = wsResourceGroupSearch;
            this.wsSearchOption = wsSearchOption;
            this.accountScope = accountScope;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBySearchResponse", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getBySearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSResourceGroupSearchResult getBySearchReturn;
        
        public getBySearchResponse()
        {
        }
        
        public getBySearchResponse(WSResourceGroupSearchServiceProxy.WSResourceGroupSearchResult getBySearchReturn)
        {
            this.getBySearchReturn = getBySearchReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdList", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getByIdListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] resourceGroupIdArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption;
        
        public getByIdListRequest()
        {
        }
        
        public getByIdListRequest(string[] resourceGroupIdArray, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption)
        {
            this.resourceGroupIdArray = resourceGroupIdArray;
            this.wsSearchOption = wsSearchOption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdListResponse", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getByIdListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSResourceGroup[] getByIdListReturn;
        
        public getByIdListResponse()
        {
        }
        
        public getByIdListResponse(WSResourceGroup[] getByIdListReturn)
        {
            this.getByIdListReturn = getByIdListReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.ws.rms.umusic.com")]
    public enum RepertoireType
    {
        
        /// <remarks/>
        RESOURCE,
        
        /// <remarks/>
        RELEASE,
        
        /// <remarks/>
        PROJECT,
        
        /// <remarks/>
        PEOPLE,
        
        /// <remarks/>
        WORK,
        
        /// <remarks/>
        COMPANY,
        
        /// <remarks/>
        RESOURCE_GROUP,
        
        /// <remarks/>
        SERIES,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByContext", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getByContextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] uniqueIdList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<RepertoireType> contextRepertoireType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption;
        
        public getByContextRequest()
        {
        }
        
        public getByContextRequest(string[] uniqueIdList, System.Nullable<RepertoireType> contextRepertoireType, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption)
        {
            this.uniqueIdList = uniqueIdList;
            this.contextRepertoireType = contextRepertoireType;
            this.wsSearchOption = wsSearchOption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByContextResponse", WrapperNamespace="http://search.ws.rms.umusic.com", IsWrapped=true)]
    public partial class getByContextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.ws.rms.umusic.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSResourceGroupSearchServiceProxy.WSResourceGroupSearchResult getByContextReturn;
        
        public getByContextResponse()
        {
        }
        
        public getByContextResponse(WSResourceGroupSearchServiceProxy.WSResourceGroupSearchResult getByContextReturn)
        {
            this.getByContextReturn = getByContextReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSResourceGroupSearchServiceChannel : WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSResourceGroupSearchServiceClient : System.ServiceModel.ClientBase<WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService>, WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService
    {
        
        public WSResourceGroupSearchServiceClient()
        {
        }
        
        public WSResourceGroupSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WSResourceGroupSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSResourceGroupSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSResourceGroupSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSResourceGroupSearchServiceProxy.getByIdResponse WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService.getById(WSResourceGroupSearchServiceProxy.getByIdRequest request)
        {
            return base.Channel.getById(request);
        }
        
        public WSResourceGroupSearchServiceProxy.WSResourceGroup getById(string resourceGroupId, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption)
        {
            WSResourceGroupSearchServiceProxy.getByIdRequest inValue = new WSResourceGroupSearchServiceProxy.getByIdRequest();
            inValue.resourceGroupId = resourceGroupId;
            inValue.wsSearchOption = wsSearchOption;
            WSResourceGroupSearchServiceProxy.getByIdResponse retVal = ((WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService)(this)).getById(inValue);
            return retVal.getByIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSResourceGroupSearchServiceProxy.getContributionsResponse WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService.getContributions(WSResourceGroupSearchServiceProxy.getContributionsRequest request)
        {
            return base.Channel.getContributions(request);
        }
        
        public WSResourceGroupSearchServiceProxy.WSResourceGroupContributionResult getContributions(WSResourceGroupSearchServiceProxy.WSResourceGroupContributionSearch wsResourceGroupContributionSearch)
        {
            WSResourceGroupSearchServiceProxy.getContributionsRequest inValue = new WSResourceGroupSearchServiceProxy.getContributionsRequest();
            inValue.wsResourceGroupContributionSearch = wsResourceGroupContributionSearch;
            WSResourceGroupSearchServiceProxy.getContributionsResponse retVal = ((WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService)(this)).getContributions(inValue);
            return retVal.getContributionsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSResourceGroupSearchServiceProxy.getBySearchResponse WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService.getBySearch(WSResourceGroupSearchServiceProxy.getBySearchRequest request)
        {
            return base.Channel.getBySearch(request);
        }
        
        public WSResourceGroupSearchServiceProxy.WSResourceGroupSearchResult getBySearch(WSResourceGroupSearchServiceProxy.WSResourceGroupSearch wsResourceGroupSearch, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption, System.Nullable<AccountScope> accountScope)
        {
            WSResourceGroupSearchServiceProxy.getBySearchRequest inValue = new WSResourceGroupSearchServiceProxy.getBySearchRequest();
            inValue.wsResourceGroupSearch = wsResourceGroupSearch;
            inValue.wsSearchOption = wsSearchOption;
            inValue.accountScope = accountScope;
            WSResourceGroupSearchServiceProxy.getBySearchResponse retVal = ((WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService)(this)).getBySearch(inValue);
            return retVal.getBySearchReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSResourceGroupSearchServiceProxy.getByIdListResponse WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService.getByIdList(WSResourceGroupSearchServiceProxy.getByIdListRequest request)
        {
            return base.Channel.getByIdList(request);
        }
        
        public WSResourceGroup[] getByIdList(string[] resourceGroupIdArray, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption)
        {
            WSResourceGroupSearchServiceProxy.getByIdListRequest inValue = new WSResourceGroupSearchServiceProxy.getByIdListRequest();
            inValue.resourceGroupIdArray = resourceGroupIdArray;
            inValue.wsSearchOption = wsSearchOption;
            WSResourceGroupSearchServiceProxy.getByIdListResponse retVal = ((WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService)(this)).getByIdList(inValue);
            return retVal.getByIdListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSResourceGroupSearchServiceProxy.getByContextResponse WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService.getByContext(WSResourceGroupSearchServiceProxy.getByContextRequest request)
        {
            return base.Channel.getByContext(request);
        }
        
        public WSResourceGroupSearchServiceProxy.WSResourceGroupSearchResult getByContext(string[] uniqueIdList, System.Nullable<RepertoireType> contextRepertoireType, WSResourceGroupSearchServiceProxy.WSSearchOption wsSearchOption)
        {
            WSResourceGroupSearchServiceProxy.getByContextRequest inValue = new WSResourceGroupSearchServiceProxy.getByContextRequest();
            inValue.uniqueIdList = uniqueIdList;
            inValue.contextRepertoireType = contextRepertoireType;
            inValue.wsSearchOption = wsSearchOption;
            WSResourceGroupSearchServiceProxy.getByContextResponse retVal = ((WSResourceGroupSearchServiceProxy.WSResourceGroupSearchService)(this)).getByContext(inValue);
            return retVal.getByContextReturn;
        }
    }
}
